version: '3.7'

services:
  kano.ess:
    image: ${DOCKER_REGISTRY-}kanoess
    build:
      context: .
      dockerfile: KANO.ESS\Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8003;http://+:8000
      - ASPNETCORE_HTTPS_PORT=8003
    ports:
      - "8000:8000"
      - "8003:8003"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro  

  kano.api.employee:
    image: ${DOCKER_REGISTRY-}kanoapiemployee
    build:
     context: .
     dockerfile: KANO.Api.Employee\Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:7002;http://+:7001
     - ASPNETCORE_HTTPS_PORT=7002   
    ports:
     - "7001:7001"
     - "7002:7002"
    volumes:
     - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
     - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro

  kano.api.benefit:
    image: ${DOCKER_REGISTRY-}kanoapibenefit
    build:
      context: .
      dockerfile: KANO.Api.Benefit\Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7004;http://+:7003
      - ASPNETCORE_HTTPS_PORT=7004
    ports:
      - "7003:7003"
      - "7004:7004"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro


  kano.api.leave:
    image: ${DOCKER_REGISTRY-}kanoapileave
    build:
      context: .
      dockerfile: KANO.Api.Leave\Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7006;http://+:7005
      - ASPNETCORE_HTTPS_PORT=7006
    ports:
      - "7005:7005"
      - "7006:7006"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro

  kano.api.timemanagement:
    image: ${DOCKER_REGISTRY-}kanoapitimemanagement
    build:
      context: .
      dockerfile: KANO.Api.TimeManagement\Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7008;http://+:7007
      - ASPNETCORE_HTTPS_PORT=7008
    ports:
      - "7007:7007"
      - "7008:7008"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro

  kano.api.auth:
    image: ${DOCKER_REGISTRY-}kanoapiauth
    build:
      context: .
      dockerfile: KANO.Api.Auth\Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7010;http://+:7009
      - ASPNETCORE_HTTPS_PORT=7010
    ports:
      - "7009:7009"
      - "7010:7010"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro

  kano.api.gateway:
    image: ${DOCKER_REGISTRY-}kanoapigateway
    build:
      context: .
      dockerfile: KANO.Api.Gateway\Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8083;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8083
    ports:
      - "8080:8080"
      - "8083:8083"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
