//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KESSCRServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object
    {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private string PartitionKeyField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser
        {
            get
            {
                return this.LogonAsUserField;
            }
            set
            {
                this.LogonAsUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRClaimCreditLimitEmpl", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class CRClaimCreditLimitEmpl : KESSCRServices.XppObjectBase
    {
        
        private decimal CreditLimitClaimField;
        
        private string DepartmentField;
        
        private string EmplIdField;
        
        private string EmplNameField;
        
        private string GradePositionField;
        
        private string GradePositionDescField;
        
        private string PositionField;
        
        private decimal SaldoClaimField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CreditLimitClaim
        {
            get
            {
                return this.CreditLimitClaimField;
            }
            set
            {
                this.CreditLimitClaimField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplId
        {
            get
            {
                return this.EmplIdField;
            }
            set
            {
                this.EmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplName
        {
            get
            {
                return this.EmplNameField;
            }
            set
            {
                this.EmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradePosition
        {
            get
            {
                return this.GradePositionField;
            }
            set
            {
                this.GradePositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradePositionDesc
        {
            get
            {
                return this.GradePositionDescField;
            }
            set
            {
                this.GradePositionDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SaldoClaim
        {
            get
            {
                return this.SaldoClaimField;
            }
            set
            {
                this.SaldoClaimField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSCRServices.CRClaimCreditLimitGrade))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSCRServices.CRClaimReimburseHealthy))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSCRServices.CRDocuRef))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSCRServices.CRClaimCreditLimitEmpl))]
    public partial class XppObjectBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRClaimCreditLimitGrade", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class CRClaimCreditLimitGrade : KESSCRServices.XppObjectBase
    {
        
        private decimal CreditLimitAmountField;
        
        private string GradePositionField;
        
        private string GradePositionDescField;
        
        private long RecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CreditLimitAmount
        {
            get
            {
                return this.CreditLimitAmountField;
            }
            set
            {
                this.CreditLimitAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradePosition
        {
            get
            {
                return this.GradePositionField;
            }
            set
            {
                this.GradePositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradePositionDesc
        {
            get
            {
                return this.GradePositionDescField;
            }
            set
            {
                this.GradePositionDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRClaimReimburseHealthy", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class CRClaimReimburseHealthy : KESSCRServices.XppObjectBase
    {
        
        private System.DateTime ClaimDateField;
        
        private string ClaimIdField;
        
        private KESSCRServices.CRDocuRef[] DocumentListField;
        
        private string EmplIdField;
        
        private string EmplNameField;
        
        private KESSCRServices.KESSFamililyRelationship FamilyRelationshipField;
        
        private KESSCRServices.KESSJenisRawat JenisRawatField;
        
        private string PasienNameField;
        
        private long RecIdField;
        
        private KESSCRServices.KESSStatusClaimReimburse StatusClaimReimburseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ClaimDate
        {
            get
            {
                return this.ClaimDateField;
            }
            set
            {
                this.ClaimDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimId
        {
            get
            {
                return this.ClaimIdField;
            }
            set
            {
                this.ClaimIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCRServices.CRDocuRef[] DocumentList
        {
            get
            {
                return this.DocumentListField;
            }
            set
            {
                this.DocumentListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplId
        {
            get
            {
                return this.EmplIdField;
            }
            set
            {
                this.EmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplName
        {
            get
            {
                return this.EmplNameField;
            }
            set
            {
                this.EmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCRServices.KESSFamililyRelationship FamilyRelationship
        {
            get
            {
                return this.FamilyRelationshipField;
            }
            set
            {
                this.FamilyRelationshipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCRServices.KESSJenisRawat JenisRawat
        {
            get
            {
                return this.JenisRawatField;
            }
            set
            {
                this.JenisRawatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasienName
        {
            get
            {
                return this.PasienNameField;
            }
            set
            {
                this.PasienNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCRServices.KESSStatusClaimReimburse StatusClaimReimburse
        {
            get
            {
                return this.StatusClaimReimburseField;
            }
            set
            {
                this.StatusClaimReimburseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRDocuRef", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class CRDocuRef : KESSCRServices.XppObjectBase
    {
        
        private decimal AmountField;
        
        private KESSCRServices.KESSDocSource DocSourceField;
        
        private string DocuNameField;
        
        private string DocumentPathField;
        
        private string NotesField;
        
        private long RecIdField;
        
        private string RefCompanyIdField;
        
        private long RefRecIdField;
        
        private int RefTableIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCRServices.KESSDocSource DocSource
        {
            get
            {
                return this.DocSourceField;
            }
            set
            {
                this.DocSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocuName
        {
            get
            {
                return this.DocuNameField;
            }
            set
            {
                this.DocuNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentPath
        {
            get
            {
                return this.DocumentPathField;
            }
            set
            {
                this.DocumentPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefCompanyId
        {
            get
            {
                return this.RefCompanyIdField;
            }
            set
            {
                this.RefCompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RefRecId
        {
            get
            {
                return this.RefRecIdField;
            }
            set
            {
                this.RefRecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RefTableId
        {
            get
            {
                return this.RefTableIdField;
            }
            set
            {
                this.RefTableIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSFamililyRelationship", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSFamililyRelationship : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Worker = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spouse = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Child = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSJenisRawat", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSJenisRawat : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RawatInap = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RawatJalan = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSStatusClaimReimburse", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSStatusClaimReimburse : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Request = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InReview = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paid = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSDocSource", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSDocSource : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Certificate = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Document = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object
    {
        
        private string CustomDetailXmlField;
        
        private KESSCRServices.FaultMessageList[] FaultMessageListArrayField;
        
        private KESSCRServices.InfologMessage[] InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml
        {
            get
            {
                return this.CustomDetailXmlField;
            }
            set
            {
                this.CustomDetailXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCRServices.FaultMessageList[] FaultMessageListArray
        {
            get
            {
                return this.FaultMessageListArrayField;
            }
            set
            {
                this.FaultMessageListArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCRServices.InfologMessage[] InfologMessageList
        {
            get
            {
                return this.InfologMessageListField;
            }
            set
            {
                this.InfologMessageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType
        {
            get
            {
                return this.XppExceptionTypeField;
            }
            set
            {
                this.XppExceptionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object
    {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private KESSCRServices.FaultMessage[] FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation
        {
            get
            {
                return this.DocumentOperationField;
            }
            set
            {
                this.DocumentOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCRServices.FaultMessage[] FaultMessageArray
        {
            get
            {
                return this.FaultMessageArrayField;
            }
            set
            {
                this.FaultMessageArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation
        {
            get
            {
                return this.ServiceOperationField;
            }
            set
            {
                this.ServiceOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter
        {
            get
            {
                return this.ServiceOperationParameterField;
            }
            set
            {
                this.ServiceOperationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine
        {
            get
            {
                return this.XmlLineField;
            }
            set
            {
                this.XmlLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition
        {
            get
            {
                return this.XmlPositionField;
            }
            set
            {
                this.XmlPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object
    {
        
        private KESSCRServices.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCRServices.InfologMessageType InfologMessageType
        {
            get
            {
                return this.InfologMessageTypeField;
            }
            set
            {
                this.InfologMessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="KESSCRServices.KESSCRService")]
    public interface KESSCRService
    {
        
        // CODEGEN: Generating message contract since the wrapper name (KESSCRServiceGetClaimCreditLimitEmplRequest) of message KESSCRServiceGetClaimCreditLimitEmplRequest does not match the default value (getClaimCreditLimitEmpl)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCRService/getClaimCreditLimitEmpl", ReplyAction="http://tempuri.org/KESSCRService/getClaimCreditLimitEmplResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSCRServices.AifFault), Action="http://tempuri.org/KESSCRService/getClaimCreditLimitEmplAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSCRServices.KESSCRServiceGetClaimCreditLimitEmplResponse getClaimCreditLimitEmpl(KESSCRServices.KESSCRServiceGetClaimCreditLimitEmplRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCRService/getClaimCreditLimitEmpl", ReplyAction="http://tempuri.org/KESSCRService/getClaimCreditLimitEmplResponse")]
        System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetClaimCreditLimitEmplResponse> getClaimCreditLimitEmplAsync(KESSCRServices.KESSCRServiceGetClaimCreditLimitEmplRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSCRServiceGetListClaimReimbursementRequest) of message KESSCRServiceGetListClaimReimbursementRequest does not match the default value (getListClaimReimbursement)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCRService/getListClaimReimbursement", ReplyAction="http://tempuri.org/KESSCRService/getListClaimReimbursementResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSCRServices.AifFault), Action="http://tempuri.org/KESSCRService/getListClaimReimbursementAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSCRServices.KESSCRServiceGetListClaimReimbursementResponse getListClaimReimbursement(KESSCRServices.KESSCRServiceGetListClaimReimbursementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCRService/getListClaimReimbursement", ReplyAction="http://tempuri.org/KESSCRService/getListClaimReimbursementResponse")]
        System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetListClaimReimbursementResponse> getListClaimReimbursementAsync(KESSCRServices.KESSCRServiceGetListClaimReimbursementRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSCRServiceGetClaimReimbursementByRecIdRequest) of message KESSCRServiceGetClaimReimbursementByRecIdRequest does not match the default value (getClaimReimbursementByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCRService/getClaimReimbursementByRecId", ReplyAction="http://tempuri.org/KESSCRService/getClaimReimbursementByRecIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSCRServices.AifFault), Action="http://tempuri.org/KESSCRService/getClaimReimbursementByRecIdAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSCRServices.KESSCRServiceGetClaimReimbursementByRecIdResponse getClaimReimbursementByRecId(KESSCRServices.KESSCRServiceGetClaimReimbursementByRecIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCRService/getClaimReimbursementByRecId", ReplyAction="http://tempuri.org/KESSCRService/getClaimReimbursementByRecIdResponse")]
        System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetClaimReimbursementByRecIdResponse> getClaimReimbursementByRecIdAsync(KESSCRServices.KESSCRServiceGetClaimReimbursementByRecIdRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSCRServiceGetClaimReimbursementRequest) of message KESSCRServiceGetClaimReimbursementRequest does not match the default value (getClaimReimbursement)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCRService/getClaimReimbursement", ReplyAction="http://tempuri.org/KESSCRService/getClaimReimbursementResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSCRServices.AifFault), Action="http://tempuri.org/KESSCRService/getClaimReimbursementAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSCRServices.KESSCRServiceGetClaimReimbursementResponse getClaimReimbursement(KESSCRServices.KESSCRServiceGetClaimReimbursementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCRService/getClaimReimbursement", ReplyAction="http://tempuri.org/KESSCRService/getClaimReimbursementResponse")]
        System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetClaimReimbursementResponse> getClaimReimbursementAsync(KESSCRServices.KESSCRServiceGetClaimReimbursementRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSCRServiceGetListClaimCreditLimitByGradeRequest) of message KESSCRServiceGetListClaimCreditLimitByGradeRequest does not match the default value (getListClaimCreditLimitByGrade)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCRService/getListClaimCreditLimitByGrade", ReplyAction="http://tempuri.org/KESSCRService/getListClaimCreditLimitByGradeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSCRServices.AifFault), Action="http://tempuri.org/KESSCRService/getListClaimCreditLimitByGradeAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSCRServices.KESSCRServiceGetListClaimCreditLimitByGradeResponse getListClaimCreditLimitByGrade(KESSCRServices.KESSCRServiceGetListClaimCreditLimitByGradeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCRService/getListClaimCreditLimitByGrade", ReplyAction="http://tempuri.org/KESSCRService/getListClaimCreditLimitByGradeResponse")]
        System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetListClaimCreditLimitByGradeResponse> getListClaimCreditLimitByGradeAsync(KESSCRServices.KESSCRServiceGetListClaimCreditLimitByGradeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCRServiceGetClaimCreditLimitEmplRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCRServiceGetClaimCreditLimitEmplRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSCRServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string emplId;
        
        public KESSCRServiceGetClaimCreditLimitEmplRequest()
        {
        }
        
        public KESSCRServiceGetClaimCreditLimitEmplRequest(KESSCRServices.CallContext CallContext, string emplId)
        {
            this.CallContext = CallContext;
            this.emplId = emplId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCRServiceGetClaimCreditLimitEmplResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCRServiceGetClaimCreditLimitEmplResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSCRServices.CRClaimCreditLimitEmpl[] response;
        
        public KESSCRServiceGetClaimCreditLimitEmplResponse()
        {
        }
        
        public KESSCRServiceGetClaimCreditLimitEmplResponse(KESSCRServices.CRClaimCreditLimitEmpl[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCRServiceGetListClaimReimbursementRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCRServiceGetListClaimReimbursementRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSCRServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string emplId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public System.DateTime startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public System.DateTime endDate;
        
        public KESSCRServiceGetListClaimReimbursementRequest()
        {
        }
        
        public KESSCRServiceGetListClaimReimbursementRequest(KESSCRServices.CallContext CallContext, string emplId, System.DateTime startDate, System.DateTime endDate)
        {
            this.CallContext = CallContext;
            this.emplId = emplId;
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCRServiceGetListClaimReimbursementResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCRServiceGetListClaimReimbursementResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSCRServices.CRClaimReimburseHealthy[] response;
        
        public KESSCRServiceGetListClaimReimbursementResponse()
        {
        }
        
        public KESSCRServiceGetListClaimReimbursementResponse(KESSCRServices.CRClaimReimburseHealthy[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCRServiceGetClaimReimbursementByRecIdRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCRServiceGetClaimReimbursementByRecIdRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSCRServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public long recId;
        
        public KESSCRServiceGetClaimReimbursementByRecIdRequest()
        {
        }
        
        public KESSCRServiceGetClaimReimbursementByRecIdRequest(KESSCRServices.CallContext CallContext, long recId)
        {
            this.CallContext = CallContext;
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCRServiceGetClaimReimbursementByRecIdResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCRServiceGetClaimReimbursementByRecIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSCRServices.CRClaimReimburseHealthy[] response;
        
        public KESSCRServiceGetClaimReimbursementByRecIdResponse()
        {
        }
        
        public KESSCRServiceGetClaimReimbursementByRecIdResponse(KESSCRServices.CRClaimReimburseHealthy[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCRServiceGetClaimReimbursementRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCRServiceGetClaimReimbursementRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSCRServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string emplId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string claimId;
        
        public KESSCRServiceGetClaimReimbursementRequest()
        {
        }
        
        public KESSCRServiceGetClaimReimbursementRequest(KESSCRServices.CallContext CallContext, string emplId, string claimId)
        {
            this.CallContext = CallContext;
            this.emplId = emplId;
            this.claimId = claimId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCRServiceGetClaimReimbursementResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCRServiceGetClaimReimbursementResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSCRServices.CRClaimReimburseHealthy[] response;
        
        public KESSCRServiceGetClaimReimbursementResponse()
        {
        }
        
        public KESSCRServiceGetClaimReimbursementResponse(KESSCRServices.CRClaimReimburseHealthy[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCRServiceGetListClaimCreditLimitByGradeRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCRServiceGetListClaimCreditLimitByGradeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSCRServices.CallContext CallContext;
        
        public KESSCRServiceGetListClaimCreditLimitByGradeRequest()
        {
        }
        
        public KESSCRServiceGetListClaimCreditLimitByGradeRequest(KESSCRServices.CallContext CallContext)
        {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCRServiceGetListClaimCreditLimitByGradeResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCRServiceGetListClaimCreditLimitByGradeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSCRServices.CRClaimCreditLimitGrade[] response;
        
        public KESSCRServiceGetListClaimCreditLimitByGradeResponse()
        {
        }
        
        public KESSCRServiceGetListClaimCreditLimitByGradeResponse(KESSCRServices.CRClaimCreditLimitGrade[] response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface KESSCRServiceChannel : KESSCRServices.KESSCRService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class KESSCRServiceClient : System.ServiceModel.ClientBase<KESSCRServices.KESSCRService>, KESSCRServices.KESSCRService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KESSCRServiceClient() : 
                base(KESSCRServiceClient.GetDefaultBinding(), KESSCRServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_KESSCRService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSCRServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(KESSCRServiceClient.GetBindingForEndpoint(endpointConfiguration), KESSCRServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSCRServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KESSCRServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSCRServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KESSCRServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSCRServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSCRServices.KESSCRServiceGetClaimCreditLimitEmplResponse KESSCRServices.KESSCRService.getClaimCreditLimitEmpl(KESSCRServices.KESSCRServiceGetClaimCreditLimitEmplRequest request)
        {
            return base.Channel.getClaimCreditLimitEmpl(request);
        }
        
        public KESSCRServices.CRClaimCreditLimitEmpl[] getClaimCreditLimitEmpl(KESSCRServices.CallContext CallContext, string emplId)
        {
            KESSCRServices.KESSCRServiceGetClaimCreditLimitEmplRequest inValue = new KESSCRServices.KESSCRServiceGetClaimCreditLimitEmplRequest();
            inValue.CallContext = CallContext;
            inValue.emplId = emplId;
            KESSCRServices.KESSCRServiceGetClaimCreditLimitEmplResponse retVal = ((KESSCRServices.KESSCRService)(this)).getClaimCreditLimitEmpl(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetClaimCreditLimitEmplResponse> KESSCRServices.KESSCRService.getClaimCreditLimitEmplAsync(KESSCRServices.KESSCRServiceGetClaimCreditLimitEmplRequest request)
        {
            return base.Channel.getClaimCreditLimitEmplAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetClaimCreditLimitEmplResponse> getClaimCreditLimitEmplAsync(KESSCRServices.CallContext CallContext, string emplId)
        {
            KESSCRServices.KESSCRServiceGetClaimCreditLimitEmplRequest inValue = new KESSCRServices.KESSCRServiceGetClaimCreditLimitEmplRequest();
            inValue.CallContext = CallContext;
            inValue.emplId = emplId;
            return ((KESSCRServices.KESSCRService)(this)).getClaimCreditLimitEmplAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSCRServices.KESSCRServiceGetListClaimReimbursementResponse KESSCRServices.KESSCRService.getListClaimReimbursement(KESSCRServices.KESSCRServiceGetListClaimReimbursementRequest request)
        {
            return base.Channel.getListClaimReimbursement(request);
        }
        
        public KESSCRServices.CRClaimReimburseHealthy[] getListClaimReimbursement(KESSCRServices.CallContext CallContext, string emplId, System.DateTime startDate, System.DateTime endDate)
        {
            KESSCRServices.KESSCRServiceGetListClaimReimbursementRequest inValue = new KESSCRServices.KESSCRServiceGetListClaimReimbursementRequest();
            inValue.CallContext = CallContext;
            inValue.emplId = emplId;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            KESSCRServices.KESSCRServiceGetListClaimReimbursementResponse retVal = ((KESSCRServices.KESSCRService)(this)).getListClaimReimbursement(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetListClaimReimbursementResponse> KESSCRServices.KESSCRService.getListClaimReimbursementAsync(KESSCRServices.KESSCRServiceGetListClaimReimbursementRequest request)
        {
            return base.Channel.getListClaimReimbursementAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetListClaimReimbursementResponse> getListClaimReimbursementAsync(KESSCRServices.CallContext CallContext, string emplId, System.DateTime startDate, System.DateTime endDate)
        {
            KESSCRServices.KESSCRServiceGetListClaimReimbursementRequest inValue = new KESSCRServices.KESSCRServiceGetListClaimReimbursementRequest();
            inValue.CallContext = CallContext;
            inValue.emplId = emplId;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            return ((KESSCRServices.KESSCRService)(this)).getListClaimReimbursementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSCRServices.KESSCRServiceGetClaimReimbursementByRecIdResponse KESSCRServices.KESSCRService.getClaimReimbursementByRecId(KESSCRServices.KESSCRServiceGetClaimReimbursementByRecIdRequest request)
        {
            return base.Channel.getClaimReimbursementByRecId(request);
        }
        
        public KESSCRServices.CRClaimReimburseHealthy[] getClaimReimbursementByRecId(KESSCRServices.CallContext CallContext, long recId)
        {
            KESSCRServices.KESSCRServiceGetClaimReimbursementByRecIdRequest inValue = new KESSCRServices.KESSCRServiceGetClaimReimbursementByRecIdRequest();
            inValue.CallContext = CallContext;
            inValue.recId = recId;
            KESSCRServices.KESSCRServiceGetClaimReimbursementByRecIdResponse retVal = ((KESSCRServices.KESSCRService)(this)).getClaimReimbursementByRecId(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetClaimReimbursementByRecIdResponse> KESSCRServices.KESSCRService.getClaimReimbursementByRecIdAsync(KESSCRServices.KESSCRServiceGetClaimReimbursementByRecIdRequest request)
        {
            return base.Channel.getClaimReimbursementByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetClaimReimbursementByRecIdResponse> getClaimReimbursementByRecIdAsync(KESSCRServices.CallContext CallContext, long recId)
        {
            KESSCRServices.KESSCRServiceGetClaimReimbursementByRecIdRequest inValue = new KESSCRServices.KESSCRServiceGetClaimReimbursementByRecIdRequest();
            inValue.CallContext = CallContext;
            inValue.recId = recId;
            return ((KESSCRServices.KESSCRService)(this)).getClaimReimbursementByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSCRServices.KESSCRServiceGetClaimReimbursementResponse KESSCRServices.KESSCRService.getClaimReimbursement(KESSCRServices.KESSCRServiceGetClaimReimbursementRequest request)
        {
            return base.Channel.getClaimReimbursement(request);
        }
        
        public KESSCRServices.CRClaimReimburseHealthy[] getClaimReimbursement(KESSCRServices.CallContext CallContext, string emplId, string claimId)
        {
            KESSCRServices.KESSCRServiceGetClaimReimbursementRequest inValue = new KESSCRServices.KESSCRServiceGetClaimReimbursementRequest();
            inValue.CallContext = CallContext;
            inValue.emplId = emplId;
            inValue.claimId = claimId;
            KESSCRServices.KESSCRServiceGetClaimReimbursementResponse retVal = ((KESSCRServices.KESSCRService)(this)).getClaimReimbursement(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetClaimReimbursementResponse> KESSCRServices.KESSCRService.getClaimReimbursementAsync(KESSCRServices.KESSCRServiceGetClaimReimbursementRequest request)
        {
            return base.Channel.getClaimReimbursementAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetClaimReimbursementResponse> getClaimReimbursementAsync(KESSCRServices.CallContext CallContext, string emplId, string claimId)
        {
            KESSCRServices.KESSCRServiceGetClaimReimbursementRequest inValue = new KESSCRServices.KESSCRServiceGetClaimReimbursementRequest();
            inValue.CallContext = CallContext;
            inValue.emplId = emplId;
            inValue.claimId = claimId;
            return ((KESSCRServices.KESSCRService)(this)).getClaimReimbursementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSCRServices.KESSCRServiceGetListClaimCreditLimitByGradeResponse KESSCRServices.KESSCRService.getListClaimCreditLimitByGrade(KESSCRServices.KESSCRServiceGetListClaimCreditLimitByGradeRequest request)
        {
            return base.Channel.getListClaimCreditLimitByGrade(request);
        }
        
        public KESSCRServices.CRClaimCreditLimitGrade[] getListClaimCreditLimitByGrade(KESSCRServices.CallContext CallContext)
        {
            KESSCRServices.KESSCRServiceGetListClaimCreditLimitByGradeRequest inValue = new KESSCRServices.KESSCRServiceGetListClaimCreditLimitByGradeRequest();
            inValue.CallContext = CallContext;
            KESSCRServices.KESSCRServiceGetListClaimCreditLimitByGradeResponse retVal = ((KESSCRServices.KESSCRService)(this)).getListClaimCreditLimitByGrade(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetListClaimCreditLimitByGradeResponse> KESSCRServices.KESSCRService.getListClaimCreditLimitByGradeAsync(KESSCRServices.KESSCRServiceGetListClaimCreditLimitByGradeRequest request)
        {
            return base.Channel.getListClaimCreditLimitByGradeAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSCRServices.KESSCRServiceGetListClaimCreditLimitByGradeResponse> getListClaimCreditLimitByGradeAsync(KESSCRServices.CallContext CallContext)
        {
            KESSCRServices.KESSCRServiceGetListClaimCreditLimitByGradeRequest inValue = new KESSCRServices.KESSCRServiceGetListClaimCreditLimitByGradeRequest();
            inValue.CallContext = CallContext;
            return ((KESSCRServices.KESSCRService)(this)).getListClaimCreditLimitByGradeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_KESSCRService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_KESSCRService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://7.172.65.217:8202/DynamicsAx/Services/KESSCRServices");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KESSCRServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_KESSCRService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KESSCRServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_KESSCRService);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_KESSCRService,
        }
    }
}
