//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KESSWFServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object
    {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private string PartitionKeyField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser
        {
            get
            {
                return this.LogonAsUserField;
            }
            set
            {
                this.LogonAsUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WFTrackingAssign", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class WFTrackingAssign : KESSWFServices.XppObjectBase
    {
        
        private KESSWFServices.NoYes ActionApproveField;
        
        private KESSWFServices.NoYes ActionCancelField;
        
        private string ActionCommentField;
        
        private System.DateTime ActionDateTimeField;
        
        private KESSWFServices.NoYes ActionDelegateField;
        
        private string ActionDelegateToEmplIdField;
        
        private string ActionDelegateToEmplNameField;
        
        private KESSWFServices.NoYes ActionRejectField;
        
        private KESSWFServices.NoYes AssignApproveField;
        
        private KESSWFServices.NoYes AssignCancelField;
        
        private KESSWFServices.NoYes AssignDelegateField;
        
        private KESSWFServices.NoYes AssignRejectField;
        
        private string AssignToEmplIdField;
        
        private string AssignToEmplNameField;
        
        private KESSWFServices.KESSWorkflowAssignType AssignTypeField;
        
        private string InstanceIdField;
        
        private long RecIdField;
        
        private KESSWFServices.KESSWorkerRequestType RequestTypeField;
        
        private int SequenceField;
        
        private System.DateTime StepCompleteDateTimeField;
        
        private int StepSequenceField;
        
        private KESSWFServices.KESSWorkflowTrackingType StepTrackingTypeField;
        
        private string SubmitByEmplIdField;
        
        private string SubmitByEmplNameField;
        
        private System.DateTime SubmitDateTimeField;
        
        private KESSWFServices.KESSWorkflowTrackingStatus TrackingStatusField;
        
        private string WorkflowIdField;
        
        private KESSWFServices.KESSWorkflowType WorkflowTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes ActionApprove
        {
            get
            {
                return this.ActionApproveField;
            }
            set
            {
                this.ActionApproveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes ActionCancel
        {
            get
            {
                return this.ActionCancelField;
            }
            set
            {
                this.ActionCancelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionComment
        {
            get
            {
                return this.ActionCommentField;
            }
            set
            {
                this.ActionCommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActionDateTime
        {
            get
            {
                return this.ActionDateTimeField;
            }
            set
            {
                this.ActionDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes ActionDelegate
        {
            get
            {
                return this.ActionDelegateField;
            }
            set
            {
                this.ActionDelegateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionDelegateToEmplId
        {
            get
            {
                return this.ActionDelegateToEmplIdField;
            }
            set
            {
                this.ActionDelegateToEmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionDelegateToEmplName
        {
            get
            {
                return this.ActionDelegateToEmplNameField;
            }
            set
            {
                this.ActionDelegateToEmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes ActionReject
        {
            get
            {
                return this.ActionRejectField;
            }
            set
            {
                this.ActionRejectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes AssignApprove
        {
            get
            {
                return this.AssignApproveField;
            }
            set
            {
                this.AssignApproveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes AssignCancel
        {
            get
            {
                return this.AssignCancelField;
            }
            set
            {
                this.AssignCancelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes AssignDelegate
        {
            get
            {
                return this.AssignDelegateField;
            }
            set
            {
                this.AssignDelegateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes AssignReject
        {
            get
            {
                return this.AssignRejectField;
            }
            set
            {
                this.AssignRejectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignToEmplId
        {
            get
            {
                return this.AssignToEmplIdField;
            }
            set
            {
                this.AssignToEmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignToEmplName
        {
            get
            {
                return this.AssignToEmplNameField;
            }
            set
            {
                this.AssignToEmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.KESSWorkflowAssignType AssignType
        {
            get
            {
                return this.AssignTypeField;
            }
            set
            {
                this.AssignTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstanceId
        {
            get
            {
                return this.InstanceIdField;
            }
            set
            {
                this.InstanceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.KESSWorkerRequestType RequestType
        {
            get
            {
                return this.RequestTypeField;
            }
            set
            {
                this.RequestTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sequence
        {
            get
            {
                return this.SequenceField;
            }
            set
            {
                this.SequenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StepCompleteDateTime
        {
            get
            {
                return this.StepCompleteDateTimeField;
            }
            set
            {
                this.StepCompleteDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StepSequence
        {
            get
            {
                return this.StepSequenceField;
            }
            set
            {
                this.StepSequenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.KESSWorkflowTrackingType StepTrackingType
        {
            get
            {
                return this.StepTrackingTypeField;
            }
            set
            {
                this.StepTrackingTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmitByEmplId
        {
            get
            {
                return this.SubmitByEmplIdField;
            }
            set
            {
                this.SubmitByEmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmitByEmplName
        {
            get
            {
                return this.SubmitByEmplNameField;
            }
            set
            {
                this.SubmitByEmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SubmitDateTime
        {
            get
            {
                return this.SubmitDateTimeField;
            }
            set
            {
                this.SubmitDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.KESSWorkflowTrackingStatus TrackingStatus
        {
            get
            {
                return this.TrackingStatusField;
            }
            set
            {
                this.TrackingStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkflowId
        {
            get
            {
                return this.WorkflowIdField;
            }
            set
            {
                this.WorkflowIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.KESSWorkflowType WorkflowType
        {
            get
            {
                return this.WorkflowTypeField;
            }
            set
            {
                this.WorkflowTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSWFServices.WFTracking))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSWFServices.WFTrackingAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSWFServices.WFTrackingAssignDelegateEmpl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSWFServices.WFTrackingAssign))]
    public partial class XppObjectBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WFTracking", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class WFTracking : KESSWFServices.XppObjectBase
    {
        
        private KESSWFServices.NoYes ActionApproveField;
        
        private KESSWFServices.NoYes ActionCancelField;
        
        private string ActionCommentField;
        
        private System.DateTime ActionDateTimeField;
        
        private KESSWFServices.NoYes ActionDelegateField;
        
        private string ActionDelegateToEmplIdField;
        
        private string ActionDelegateToEmplNameField;
        
        private KESSWFServices.NoYes ActionRejectField;
        
        private string AssignToEmplIdField;
        
        private string AssignToEmplNameField;
        
        private KESSWFServices.KESSWorkflowAssignType AssignTypeField;
        
        private System.DateTime CompleteDateTimeField;
        
        private string InstanceIdField;
        
        private KESSWFServices.KESSWorkerRequestType RequestTypeField;
        
        private System.DateTime StepCompleteDateTimeField;
        
        private System.DateTime StepCompletionDateTimeField;
        
        private KESSWFServices.KESSWorkflowStepCompletionPolicy StepCompletionPolicyField;
        
        private string StepNameField;
        
        private int StepSequenceField;
        
        private KESSWFServices.KESSWorkflowTrackingType StepTrackingTypeField;
        
        private string SubmitByEmplIdField;
        
        private string SubmitByEmplNameField;
        
        private System.DateTime SubmitDateTimeField;
        
        private KESSWFServices.KESSWorkflowTrackingStatus TrackingStatusField;
        
        private string WorkflowIdField;
        
        private KESSWFServices.KESSWorkflowType WorkflowTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes ActionApprove
        {
            get
            {
                return this.ActionApproveField;
            }
            set
            {
                this.ActionApproveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes ActionCancel
        {
            get
            {
                return this.ActionCancelField;
            }
            set
            {
                this.ActionCancelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionComment
        {
            get
            {
                return this.ActionCommentField;
            }
            set
            {
                this.ActionCommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActionDateTime
        {
            get
            {
                return this.ActionDateTimeField;
            }
            set
            {
                this.ActionDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes ActionDelegate
        {
            get
            {
                return this.ActionDelegateField;
            }
            set
            {
                this.ActionDelegateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionDelegateToEmplId
        {
            get
            {
                return this.ActionDelegateToEmplIdField;
            }
            set
            {
                this.ActionDelegateToEmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionDelegateToEmplName
        {
            get
            {
                return this.ActionDelegateToEmplNameField;
            }
            set
            {
                this.ActionDelegateToEmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes ActionReject
        {
            get
            {
                return this.ActionRejectField;
            }
            set
            {
                this.ActionRejectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignToEmplId
        {
            get
            {
                return this.AssignToEmplIdField;
            }
            set
            {
                this.AssignToEmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignToEmplName
        {
            get
            {
                return this.AssignToEmplNameField;
            }
            set
            {
                this.AssignToEmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.KESSWorkflowAssignType AssignType
        {
            get
            {
                return this.AssignTypeField;
            }
            set
            {
                this.AssignTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CompleteDateTime
        {
            get
            {
                return this.CompleteDateTimeField;
            }
            set
            {
                this.CompleteDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstanceId
        {
            get
            {
                return this.InstanceIdField;
            }
            set
            {
                this.InstanceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.KESSWorkerRequestType RequestType
        {
            get
            {
                return this.RequestTypeField;
            }
            set
            {
                this.RequestTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StepCompleteDateTime
        {
            get
            {
                return this.StepCompleteDateTimeField;
            }
            set
            {
                this.StepCompleteDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StepCompletionDateTime
        {
            get
            {
                return this.StepCompletionDateTimeField;
            }
            set
            {
                this.StepCompletionDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.KESSWorkflowStepCompletionPolicy StepCompletionPolicy
        {
            get
            {
                return this.StepCompletionPolicyField;
            }
            set
            {
                this.StepCompletionPolicyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StepName
        {
            get
            {
                return this.StepNameField;
            }
            set
            {
                this.StepNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StepSequence
        {
            get
            {
                return this.StepSequenceField;
            }
            set
            {
                this.StepSequenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.KESSWorkflowTrackingType StepTrackingType
        {
            get
            {
                return this.StepTrackingTypeField;
            }
            set
            {
                this.StepTrackingTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmitByEmplId
        {
            get
            {
                return this.SubmitByEmplIdField;
            }
            set
            {
                this.SubmitByEmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmitByEmplName
        {
            get
            {
                return this.SubmitByEmplNameField;
            }
            set
            {
                this.SubmitByEmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SubmitDateTime
        {
            get
            {
                return this.SubmitDateTimeField;
            }
            set
            {
                this.SubmitDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.KESSWorkflowTrackingStatus TrackingStatus
        {
            get
            {
                return this.TrackingStatusField;
            }
            set
            {
                this.TrackingStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkflowId
        {
            get
            {
                return this.WorkflowIdField;
            }
            set
            {
                this.WorkflowIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.KESSWorkflowType WorkflowType
        {
            get
            {
                return this.WorkflowTypeField;
            }
            set
            {
                this.WorkflowTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WFTrackingAction", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class WFTrackingAction : KESSWFServices.XppObjectBase
    {
        
        private KESSWFServices.NoYes ActionApproveField;
        
        private KESSWFServices.NoYes ActionCancelField;
        
        private string ActionCommentField;
        
        private KESSWFServices.NoYes ActionDelegateField;
        
        private string ActionDelegateToEmplIdField;
        
        private KESSWFServices.NoYes ActionRejectField;
        
        private long RecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes ActionApprove
        {
            get
            {
                return this.ActionApproveField;
            }
            set
            {
                this.ActionApproveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes ActionCancel
        {
            get
            {
                return this.ActionCancelField;
            }
            set
            {
                this.ActionCancelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionComment
        {
            get
            {
                return this.ActionCommentField;
            }
            set
            {
                this.ActionCommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes ActionDelegate
        {
            get
            {
                return this.ActionDelegateField;
            }
            set
            {
                this.ActionDelegateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionDelegateToEmplId
        {
            get
            {
                return this.ActionDelegateToEmplIdField;
            }
            set
            {
                this.ActionDelegateToEmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.NoYes ActionReject
        {
            get
            {
                return this.ActionRejectField;
            }
            set
            {
                this.ActionRejectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WFTrackingAssignDelegateEmpl", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class WFTrackingAssignDelegateEmpl : KESSWFServices.XppObjectBase
    {
        
        private string EmplIdField;
        
        private string EmplNameField;
        
        private long RecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplId
        {
            get
            {
                return this.EmplIdField;
            }
            set
            {
                this.EmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplName
        {
            get
            {
                return this.EmplNameField;
            }
            set
            {
                this.EmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoYes", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    public enum NoYes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSWorkflowAssignType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSWorkflowAssignType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Originator = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Worker = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkerGroup = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReportTo = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSWorkerRequestType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSWorkerRequestType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HCMResume = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HCMPersonContact = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HCMPersonCourse = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HCMPersonCertificate = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LMLeave = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TMSchedule = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TETravelRequest = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRClaimReimbursement = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRMRecruitment = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MPPPensiun = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CNTickets = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CNVoucherCanteen = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HCMWorkerDocReq = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSWorkflowTrackingType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSWorkflowTrackingType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Creation = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approval = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completion = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancellation = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejection = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSWorkflowTrackingStatus", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSWorkflowTrackingStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InReview = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSWorkflowType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSWorkflowType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HCM = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TM = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LM = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TEReq = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRM = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MPP = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CNT = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CNV = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSWorkflowStepCompletionPolicy", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSWorkflowStepCompletionPolicy : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Single = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object
    {
        
        private string CustomDetailXmlField;
        
        private KESSWFServices.FaultMessageList[] FaultMessageListArrayField;
        
        private KESSWFServices.InfologMessage[] InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml
        {
            get
            {
                return this.CustomDetailXmlField;
            }
            set
            {
                this.CustomDetailXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.FaultMessageList[] FaultMessageListArray
        {
            get
            {
                return this.FaultMessageListArrayField;
            }
            set
            {
                this.FaultMessageListArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.InfologMessage[] InfologMessageList
        {
            get
            {
                return this.InfologMessageListField;
            }
            set
            {
                this.InfologMessageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType
        {
            get
            {
                return this.XppExceptionTypeField;
            }
            set
            {
                this.XppExceptionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object
    {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private KESSWFServices.FaultMessage[] FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation
        {
            get
            {
                return this.DocumentOperationField;
            }
            set
            {
                this.DocumentOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.FaultMessage[] FaultMessageArray
        {
            get
            {
                return this.FaultMessageArrayField;
            }
            set
            {
                this.FaultMessageArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation
        {
            get
            {
                return this.ServiceOperationField;
            }
            set
            {
                this.ServiceOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter
        {
            get
            {
                return this.ServiceOperationParameterField;
            }
            set
            {
                this.ServiceOperationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine
        {
            get
            {
                return this.XmlLineField;
            }
            set
            {
                this.XmlLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition
        {
            get
            {
                return this.XmlPositionField;
            }
            set
            {
                this.XmlPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object
    {
        
        private KESSWFServices.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSWFServices.InfologMessageType InfologMessageType
        {
            get
            {
                return this.InfologMessageTypeField;
            }
            set
            {
                this.InfologMessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="KESSWFServices.KESSWFService")]
    public interface KESSWFService
    {
        
        // CODEGEN: Generating message contract since the wrapper name (KESSWFServiceGetWFTrackingAssignFilterDateRequest) of message KESSWFServiceGetWFTrackingAssignFilterDateRequest does not match the default value (getWFTrackingAssignFilterDate)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSWFService/getWFTrackingAssignFilterDate", ReplyAction="http://tempuri.org/KESSWFService/getWFTrackingAssignFilterDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSWFServices.AifFault), Action="http://tempuri.org/KESSWFService/getWFTrackingAssignFilterDateAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSWFServices.KESSWFServiceGetWFTrackingAssignFilterDateResponse getWFTrackingAssignFilterDate(KESSWFServices.KESSWFServiceGetWFTrackingAssignFilterDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSWFService/getWFTrackingAssignFilterDate", ReplyAction="http://tempuri.org/KESSWFService/getWFTrackingAssignFilterDateResponse")]
        System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingAssignFilterDateResponse> getWFTrackingAssignFilterDateAsync(KESSWFServices.KESSWFServiceGetWFTrackingAssignFilterDateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSWFServiceGetWFTrackingAssignDelegateEmplRequest) of message KESSWFServiceGetWFTrackingAssignDelegateEmplRequest does not match the default value (getWFTrackingAssignDelegateEmpl)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSWFService/getWFTrackingAssignDelegateEmpl", ReplyAction="http://tempuri.org/KESSWFService/getWFTrackingAssignDelegateEmplResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSWFServices.AifFault), Action="http://tempuri.org/KESSWFService/getWFTrackingAssignDelegateEmplAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSWFServices.KESSWFServiceGetWFTrackingAssignDelegateEmplResponse getWFTrackingAssignDelegateEmpl(KESSWFServices.KESSWFServiceGetWFTrackingAssignDelegateEmplRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSWFService/getWFTrackingAssignDelegateEmpl", ReplyAction="http://tempuri.org/KESSWFService/getWFTrackingAssignDelegateEmplResponse")]
        System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingAssignDelegateEmplResponse> getWFTrackingAssignDelegateEmplAsync(KESSWFServices.KESSWFServiceGetWFTrackingAssignDelegateEmplRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSWFServiceGetWFTrackingRequest) of message KESSWFServiceGetWFTrackingRequest does not match the default value (getWFTracking)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSWFService/getWFTracking", ReplyAction="http://tempuri.org/KESSWFService/getWFTrackingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSWFServices.AifFault), Action="http://tempuri.org/KESSWFService/getWFTrackingAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSWFServices.KESSWFServiceGetWFTrackingResponse getWFTracking(KESSWFServices.KESSWFServiceGetWFTrackingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSWFService/getWFTracking", ReplyAction="http://tempuri.org/KESSWFService/getWFTrackingResponse")]
        System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingResponse> getWFTrackingAsync(KESSWFServices.KESSWFServiceGetWFTrackingRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSWFServiceGetWFTrackingFilterDateRequest) of message KESSWFServiceGetWFTrackingFilterDateRequest does not match the default value (getWFTrackingFilterDate)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSWFService/getWFTrackingFilterDate", ReplyAction="http://tempuri.org/KESSWFService/getWFTrackingFilterDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSWFServices.AifFault), Action="http://tempuri.org/KESSWFService/getWFTrackingFilterDateAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSWFServices.KESSWFServiceGetWFTrackingFilterDateResponse getWFTrackingFilterDate(KESSWFServices.KESSWFServiceGetWFTrackingFilterDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSWFService/getWFTrackingFilterDate", ReplyAction="http://tempuri.org/KESSWFService/getWFTrackingFilterDateResponse")]
        System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingFilterDateResponse> getWFTrackingFilterDateAsync(KESSWFServices.KESSWFServiceGetWFTrackingFilterDateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSWFServiceUpdWFTrackingActionRequest) of message KESSWFServiceUpdWFTrackingActionRequest does not match the default value (updWFTrackingAction)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSWFService/updWFTrackingAction", ReplyAction="http://tempuri.org/KESSWFService/updWFTrackingActionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSWFServices.AifFault), Action="http://tempuri.org/KESSWFService/updWFTrackingActionAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSWFServices.KESSWFServiceUpdWFTrackingActionResponse updWFTrackingAction(KESSWFServices.KESSWFServiceUpdWFTrackingActionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSWFService/updWFTrackingAction", ReplyAction="http://tempuri.org/KESSWFService/updWFTrackingActionResponse")]
        System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceUpdWFTrackingActionResponse> updWFTrackingActionAsync(KESSWFServices.KESSWFServiceUpdWFTrackingActionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSWFServiceGetWFTrackingAssignRequest) of message KESSWFServiceGetWFTrackingAssignRequest does not match the default value (getWFTrackingAssign)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSWFService/getWFTrackingAssign", ReplyAction="http://tempuri.org/KESSWFService/getWFTrackingAssignResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSWFServices.AifFault), Action="http://tempuri.org/KESSWFService/getWFTrackingAssignAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSWFServices.KESSWFServiceGetWFTrackingAssignResponse getWFTrackingAssign(KESSWFServices.KESSWFServiceGetWFTrackingAssignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSWFService/getWFTrackingAssign", ReplyAction="http://tempuri.org/KESSWFService/getWFTrackingAssignResponse")]
        System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingAssignResponse> getWFTrackingAssignAsync(KESSWFServices.KESSWFServiceGetWFTrackingAssignRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSWFServiceGetWFTrackingAssignFilterDateRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSWFServiceGetWFTrackingAssignFilterDateRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSWFServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _emplId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public System.DateTime startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public System.DateTime endDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public bool _isApproval;
        
        public KESSWFServiceGetWFTrackingAssignFilterDateRequest()
        {
        }
        
        public KESSWFServiceGetWFTrackingAssignFilterDateRequest(KESSWFServices.CallContext CallContext, string _emplId, System.DateTime startDate, System.DateTime endDate, bool _isApproval)
        {
            this.CallContext = CallContext;
            this._emplId = _emplId;
            this.startDate = startDate;
            this.endDate = endDate;
            this._isApproval = _isApproval;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSWFServiceGetWFTrackingAssignFilterDateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSWFServiceGetWFTrackingAssignFilterDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSWFServices.WFTrackingAssign[] response;
        
        public KESSWFServiceGetWFTrackingAssignFilterDateResponse()
        {
        }
        
        public KESSWFServiceGetWFTrackingAssignFilterDateResponse(KESSWFServices.WFTrackingAssign[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSWFServiceGetWFTrackingAssignDelegateEmplRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSWFServiceGetWFTrackingAssignDelegateEmplRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSWFServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public long _recId;
        
        public KESSWFServiceGetWFTrackingAssignDelegateEmplRequest()
        {
        }
        
        public KESSWFServiceGetWFTrackingAssignDelegateEmplRequest(KESSWFServices.CallContext CallContext, long _recId)
        {
            this.CallContext = CallContext;
            this._recId = _recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSWFServiceGetWFTrackingAssignDelegateEmplResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSWFServiceGetWFTrackingAssignDelegateEmplResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSWFServices.WFTrackingAssignDelegateEmpl[] response;
        
        public KESSWFServiceGetWFTrackingAssignDelegateEmplResponse()
        {
        }
        
        public KESSWFServiceGetWFTrackingAssignDelegateEmplResponse(KESSWFServices.WFTrackingAssignDelegateEmpl[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSWFServiceGetWFTrackingRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSWFServiceGetWFTrackingRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSWFServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _emplId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _instanceId;
        
        public KESSWFServiceGetWFTrackingRequest()
        {
        }
        
        public KESSWFServiceGetWFTrackingRequest(KESSWFServices.CallContext CallContext, string _emplId, string _instanceId)
        {
            this.CallContext = CallContext;
            this._emplId = _emplId;
            this._instanceId = _instanceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSWFServiceGetWFTrackingResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSWFServiceGetWFTrackingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSWFServices.WFTracking[] response;
        
        public KESSWFServiceGetWFTrackingResponse()
        {
        }
        
        public KESSWFServiceGetWFTrackingResponse(KESSWFServices.WFTracking[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSWFServiceGetWFTrackingFilterDateRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSWFServiceGetWFTrackingFilterDateRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSWFServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _emplId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public System.DateTime startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public System.DateTime endDate;
        
        public KESSWFServiceGetWFTrackingFilterDateRequest()
        {
        }
        
        public KESSWFServiceGetWFTrackingFilterDateRequest(KESSWFServices.CallContext CallContext, string _emplId, System.DateTime startDate, System.DateTime endDate)
        {
            this.CallContext = CallContext;
            this._emplId = _emplId;
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSWFServiceGetWFTrackingFilterDateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSWFServiceGetWFTrackingFilterDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSWFServices.WFTracking[] response;
        
        public KESSWFServiceGetWFTrackingFilterDateResponse()
        {
        }
        
        public KESSWFServiceGetWFTrackingFilterDateResponse(KESSWFServices.WFTracking[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSWFServiceUpdWFTrackingActionRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSWFServiceUpdWFTrackingActionRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSWFServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSWFServices.WFTrackingAction _trackingAction;
        
        public KESSWFServiceUpdWFTrackingActionRequest()
        {
        }
        
        public KESSWFServiceUpdWFTrackingActionRequest(KESSWFServices.CallContext CallContext, KESSWFServices.WFTrackingAction _trackingAction)
        {
            this.CallContext = CallContext;
            this._trackingAction = _trackingAction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSWFServiceUpdWFTrackingActionResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSWFServiceUpdWFTrackingActionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public KESSWFServiceUpdWFTrackingActionResponse()
        {
        }
        
        public KESSWFServiceUpdWFTrackingActionResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSWFServiceGetWFTrackingAssignRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSWFServiceGetWFTrackingAssignRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSWFServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _emplId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public bool _isApproval;
        
        public KESSWFServiceGetWFTrackingAssignRequest()
        {
        }
        
        public KESSWFServiceGetWFTrackingAssignRequest(KESSWFServices.CallContext CallContext, string _emplId, bool _isApproval)
        {
            this.CallContext = CallContext;
            this._emplId = _emplId;
            this._isApproval = _isApproval;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSWFServiceGetWFTrackingAssignResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSWFServiceGetWFTrackingAssignResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSWFServices.WFTrackingAssign[] response;
        
        public KESSWFServiceGetWFTrackingAssignResponse()
        {
        }
        
        public KESSWFServiceGetWFTrackingAssignResponse(KESSWFServices.WFTrackingAssign[] response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface KESSWFServiceChannel : KESSWFServices.KESSWFService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class KESSWFServiceClient : System.ServiceModel.ClientBase<KESSWFServices.KESSWFService>, KESSWFServices.KESSWFService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KESSWFServiceClient() : 
                base(KESSWFServiceClient.GetDefaultBinding(), KESSWFServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_KESSWFService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSWFServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(KESSWFServiceClient.GetBindingForEndpoint(endpointConfiguration), KESSWFServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSWFServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KESSWFServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSWFServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KESSWFServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSWFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSWFServices.KESSWFServiceGetWFTrackingAssignFilterDateResponse KESSWFServices.KESSWFService.getWFTrackingAssignFilterDate(KESSWFServices.KESSWFServiceGetWFTrackingAssignFilterDateRequest request)
        {
            return base.Channel.getWFTrackingAssignFilterDate(request);
        }
        
        public KESSWFServices.WFTrackingAssign[] getWFTrackingAssignFilterDate(KESSWFServices.CallContext CallContext, string _emplId, System.DateTime startDate, System.DateTime endDate, bool _isApproval)
        {
            KESSWFServices.KESSWFServiceGetWFTrackingAssignFilterDateRequest inValue = new KESSWFServices.KESSWFServiceGetWFTrackingAssignFilterDateRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            inValue._isApproval = _isApproval;
            KESSWFServices.KESSWFServiceGetWFTrackingAssignFilterDateResponse retVal = ((KESSWFServices.KESSWFService)(this)).getWFTrackingAssignFilterDate(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingAssignFilterDateResponse> KESSWFServices.KESSWFService.getWFTrackingAssignFilterDateAsync(KESSWFServices.KESSWFServiceGetWFTrackingAssignFilterDateRequest request)
        {
            return base.Channel.getWFTrackingAssignFilterDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingAssignFilterDateResponse> getWFTrackingAssignFilterDateAsync(KESSWFServices.CallContext CallContext, string _emplId, System.DateTime startDate, System.DateTime endDate, bool _isApproval)
        {
            KESSWFServices.KESSWFServiceGetWFTrackingAssignFilterDateRequest inValue = new KESSWFServices.KESSWFServiceGetWFTrackingAssignFilterDateRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            inValue._isApproval = _isApproval;
            return ((KESSWFServices.KESSWFService)(this)).getWFTrackingAssignFilterDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSWFServices.KESSWFServiceGetWFTrackingAssignDelegateEmplResponse KESSWFServices.KESSWFService.getWFTrackingAssignDelegateEmpl(KESSWFServices.KESSWFServiceGetWFTrackingAssignDelegateEmplRequest request)
        {
            return base.Channel.getWFTrackingAssignDelegateEmpl(request);
        }
        
        public KESSWFServices.WFTrackingAssignDelegateEmpl[] getWFTrackingAssignDelegateEmpl(KESSWFServices.CallContext CallContext, long _recId)
        {
            KESSWFServices.KESSWFServiceGetWFTrackingAssignDelegateEmplRequest inValue = new KESSWFServices.KESSWFServiceGetWFTrackingAssignDelegateEmplRequest();
            inValue.CallContext = CallContext;
            inValue._recId = _recId;
            KESSWFServices.KESSWFServiceGetWFTrackingAssignDelegateEmplResponse retVal = ((KESSWFServices.KESSWFService)(this)).getWFTrackingAssignDelegateEmpl(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingAssignDelegateEmplResponse> KESSWFServices.KESSWFService.getWFTrackingAssignDelegateEmplAsync(KESSWFServices.KESSWFServiceGetWFTrackingAssignDelegateEmplRequest request)
        {
            return base.Channel.getWFTrackingAssignDelegateEmplAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingAssignDelegateEmplResponse> getWFTrackingAssignDelegateEmplAsync(KESSWFServices.CallContext CallContext, long _recId)
        {
            KESSWFServices.KESSWFServiceGetWFTrackingAssignDelegateEmplRequest inValue = new KESSWFServices.KESSWFServiceGetWFTrackingAssignDelegateEmplRequest();
            inValue.CallContext = CallContext;
            inValue._recId = _recId;
            return ((KESSWFServices.KESSWFService)(this)).getWFTrackingAssignDelegateEmplAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSWFServices.KESSWFServiceGetWFTrackingResponse KESSWFServices.KESSWFService.getWFTracking(KESSWFServices.KESSWFServiceGetWFTrackingRequest request)
        {
            return base.Channel.getWFTracking(request);
        }
        
        public KESSWFServices.WFTracking[] getWFTracking(KESSWFServices.CallContext CallContext, string _emplId, string _instanceId)
        {
            KESSWFServices.KESSWFServiceGetWFTrackingRequest inValue = new KESSWFServices.KESSWFServiceGetWFTrackingRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            inValue._instanceId = _instanceId;
            KESSWFServices.KESSWFServiceGetWFTrackingResponse retVal = ((KESSWFServices.KESSWFService)(this)).getWFTracking(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingResponse> KESSWFServices.KESSWFService.getWFTrackingAsync(KESSWFServices.KESSWFServiceGetWFTrackingRequest request)
        {
            return base.Channel.getWFTrackingAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingResponse> getWFTrackingAsync(KESSWFServices.CallContext CallContext, string _emplId, string _instanceId)
        {
            KESSWFServices.KESSWFServiceGetWFTrackingRequest inValue = new KESSWFServices.KESSWFServiceGetWFTrackingRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            inValue._instanceId = _instanceId;
            return ((KESSWFServices.KESSWFService)(this)).getWFTrackingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSWFServices.KESSWFServiceGetWFTrackingFilterDateResponse KESSWFServices.KESSWFService.getWFTrackingFilterDate(KESSWFServices.KESSWFServiceGetWFTrackingFilterDateRequest request)
        {
            return base.Channel.getWFTrackingFilterDate(request);
        }
        
        public KESSWFServices.WFTracking[] getWFTrackingFilterDate(KESSWFServices.CallContext CallContext, string _emplId, System.DateTime startDate, System.DateTime endDate)
        {
            KESSWFServices.KESSWFServiceGetWFTrackingFilterDateRequest inValue = new KESSWFServices.KESSWFServiceGetWFTrackingFilterDateRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            KESSWFServices.KESSWFServiceGetWFTrackingFilterDateResponse retVal = ((KESSWFServices.KESSWFService)(this)).getWFTrackingFilterDate(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingFilterDateResponse> KESSWFServices.KESSWFService.getWFTrackingFilterDateAsync(KESSWFServices.KESSWFServiceGetWFTrackingFilterDateRequest request)
        {
            return base.Channel.getWFTrackingFilterDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingFilterDateResponse> getWFTrackingFilterDateAsync(KESSWFServices.CallContext CallContext, string _emplId, System.DateTime startDate, System.DateTime endDate)
        {
            KESSWFServices.KESSWFServiceGetWFTrackingFilterDateRequest inValue = new KESSWFServices.KESSWFServiceGetWFTrackingFilterDateRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            return ((KESSWFServices.KESSWFService)(this)).getWFTrackingFilterDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSWFServices.KESSWFServiceUpdWFTrackingActionResponse KESSWFServices.KESSWFService.updWFTrackingAction(KESSWFServices.KESSWFServiceUpdWFTrackingActionRequest request)
        {
            return base.Channel.updWFTrackingAction(request);
        }
        
        public string updWFTrackingAction(KESSWFServices.CallContext CallContext, KESSWFServices.WFTrackingAction _trackingAction)
        {
            KESSWFServices.KESSWFServiceUpdWFTrackingActionRequest inValue = new KESSWFServices.KESSWFServiceUpdWFTrackingActionRequest();
            inValue.CallContext = CallContext;
            inValue._trackingAction = _trackingAction;
            KESSWFServices.KESSWFServiceUpdWFTrackingActionResponse retVal = ((KESSWFServices.KESSWFService)(this)).updWFTrackingAction(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceUpdWFTrackingActionResponse> KESSWFServices.KESSWFService.updWFTrackingActionAsync(KESSWFServices.KESSWFServiceUpdWFTrackingActionRequest request)
        {
            return base.Channel.updWFTrackingActionAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceUpdWFTrackingActionResponse> updWFTrackingActionAsync(KESSWFServices.CallContext CallContext, KESSWFServices.WFTrackingAction _trackingAction)
        {
            KESSWFServices.KESSWFServiceUpdWFTrackingActionRequest inValue = new KESSWFServices.KESSWFServiceUpdWFTrackingActionRequest();
            inValue.CallContext = CallContext;
            inValue._trackingAction = _trackingAction;
            return ((KESSWFServices.KESSWFService)(this)).updWFTrackingActionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSWFServices.KESSWFServiceGetWFTrackingAssignResponse KESSWFServices.KESSWFService.getWFTrackingAssign(KESSWFServices.KESSWFServiceGetWFTrackingAssignRequest request)
        {
            return base.Channel.getWFTrackingAssign(request);
        }
        
        public KESSWFServices.WFTrackingAssign[] getWFTrackingAssign(KESSWFServices.CallContext CallContext, string _emplId, bool _isApproval)
        {
            KESSWFServices.KESSWFServiceGetWFTrackingAssignRequest inValue = new KESSWFServices.KESSWFServiceGetWFTrackingAssignRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            inValue._isApproval = _isApproval;
            KESSWFServices.KESSWFServiceGetWFTrackingAssignResponse retVal = ((KESSWFServices.KESSWFService)(this)).getWFTrackingAssign(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingAssignResponse> KESSWFServices.KESSWFService.getWFTrackingAssignAsync(KESSWFServices.KESSWFServiceGetWFTrackingAssignRequest request)
        {
            return base.Channel.getWFTrackingAssignAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSWFServices.KESSWFServiceGetWFTrackingAssignResponse> getWFTrackingAssignAsync(KESSWFServices.CallContext CallContext, string _emplId, bool _isApproval)
        {
            KESSWFServices.KESSWFServiceGetWFTrackingAssignRequest inValue = new KESSWFServices.KESSWFServiceGetWFTrackingAssignRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            inValue._isApproval = _isApproval;
            return ((KESSWFServices.KESSWFService)(this)).getWFTrackingAssignAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_KESSWFService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_KESSWFService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://7.172.65.217:8202/DynamicsAx/Services/KESSWFServices");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KESSWFServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_KESSWFService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KESSWFServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_KESSWFService);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_KESSWFService,
        }
    }
}
