//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KESSCNTServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object
    {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private string PartitionKeyField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser
        {
            get
            {
                return this.LogonAsUserField;
            }
            set
            {
                this.LogonAsUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplaintsTicket", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class ComplaintsTicket : KESSCNTServices.XppObjectBase
    {
        
        private string ComplaintsIdField;
        
        private string DescriptionField;
        
        private string DocumentPathField;
        
        private string EmailCCField;
        
        private string EmailFromField;
        
        private string EmplIdField;
        
        private string EmplNameField;
        
        private long RecIdField;
        
        private string SubjectField;
        
        private System.DateTime TicketDateField;
        
        private KESSCNTServices.KESSTicketMedia TicketMediaField;
        
        private KESSCNTServices.KESSTicketStatus TicketStatusField;
        
        private KESSCNTServices.KESSTicketType TicketTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComplaintsId
        {
            get
            {
                return this.ComplaintsIdField;
            }
            set
            {
                this.ComplaintsIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentPath
        {
            get
            {
                return this.DocumentPathField;
            }
            set
            {
                this.DocumentPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailCC
        {
            get
            {
                return this.EmailCCField;
            }
            set
            {
                this.EmailCCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailFrom
        {
            get
            {
                return this.EmailFromField;
            }
            set
            {
                this.EmailFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplId
        {
            get
            {
                return this.EmplIdField;
            }
            set
            {
                this.EmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplName
        {
            get
            {
                return this.EmplNameField;
            }
            set
            {
                this.EmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TicketDate
        {
            get
            {
                return this.TicketDateField;
            }
            set
            {
                this.TicketDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCNTServices.KESSTicketMedia TicketMedia
        {
            get
            {
                return this.TicketMediaField;
            }
            set
            {
                this.TicketMediaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCNTServices.KESSTicketStatus TicketStatus
        {
            get
            {
                return this.TicketStatusField;
            }
            set
            {
                this.TicketStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCNTServices.KESSTicketType TicketType
        {
            get
            {
                return this.TicketTypeField;
            }
            set
            {
                this.TicketTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSCNTServices.KESSAgenda))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSCNTServices.CRDocuRef))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSCNTServices.ComplaintsTicket))]
    public partial class XppObjectBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSAgenda", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class KESSAgenda : KESSCNTServices.XppObjectBase
    {
        
        private System.DateTime AgendaDateEndField;
        
        private System.DateTime AgendaDateStartField;
        
        private KESSCNTServices.KESSAgendaForType AgendaForTypeField;
        
        private string AgendaNameField;
        
        private string DescriptionField;
        
        private KESSCNTServices.CRDocuRef[] DocumentListField;
        
        private string EmplIdListField;
        
        private string IssuerField;
        
        private string LocationField;
        
        private string NotesField;
        
        private long RecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AgendaDateEnd
        {
            get
            {
                return this.AgendaDateEndField;
            }
            set
            {
                this.AgendaDateEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AgendaDateStart
        {
            get
            {
                return this.AgendaDateStartField;
            }
            set
            {
                this.AgendaDateStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCNTServices.KESSAgendaForType AgendaForType
        {
            get
            {
                return this.AgendaForTypeField;
            }
            set
            {
                this.AgendaForTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgendaName
        {
            get
            {
                return this.AgendaNameField;
            }
            set
            {
                this.AgendaNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCNTServices.CRDocuRef[] DocumentList
        {
            get
            {
                return this.DocumentListField;
            }
            set
            {
                this.DocumentListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplIdList
        {
            get
            {
                return this.EmplIdListField;
            }
            set
            {
                this.EmplIdListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issuer
        {
            get
            {
                return this.IssuerField;
            }
            set
            {
                this.IssuerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRDocuRef", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class CRDocuRef : KESSCNTServices.XppObjectBase
    {
        
        private decimal AmountField;
        
        private KESSCNTServices.KESSDocSource DocSourceField;
        
        private string DocuNameField;
        
        private string DocumentPathField;
        
        private string NotesField;
        
        private long RecIdField;
        
        private string RefCompanyIdField;
        
        private long RefRecIdField;
        
        private int RefTableIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCNTServices.KESSDocSource DocSource
        {
            get
            {
                return this.DocSourceField;
            }
            set
            {
                this.DocSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocuName
        {
            get
            {
                return this.DocuNameField;
            }
            set
            {
                this.DocuNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentPath
        {
            get
            {
                return this.DocumentPathField;
            }
            set
            {
                this.DocumentPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefCompanyId
        {
            get
            {
                return this.RefCompanyIdField;
            }
            set
            {
                this.RefCompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RefRecId
        {
            get
            {
                return this.RefRecIdField;
            }
            set
            {
                this.RefRecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RefTableId
        {
            get
            {
                return this.RefTableIdField;
            }
            set
            {
                this.RefTableIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSTicketMedia", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSTicketMedia : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Telephone = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WalkInCustomer = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSTicketStatus", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSTicketStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Open = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Progress = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Closed = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSTicketType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSTicketType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Complaint = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Questions = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Incident = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FutureRequest = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSAgendaForType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSAgendaForType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Employee = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSDocSource", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSDocSource : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Certificate = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Document = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object
    {
        
        private string CustomDetailXmlField;
        
        private KESSCNTServices.FaultMessageList[] FaultMessageListArrayField;
        
        private KESSCNTServices.InfologMessage[] InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml
        {
            get
            {
                return this.CustomDetailXmlField;
            }
            set
            {
                this.CustomDetailXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCNTServices.FaultMessageList[] FaultMessageListArray
        {
            get
            {
                return this.FaultMessageListArrayField;
            }
            set
            {
                this.FaultMessageListArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCNTServices.InfologMessage[] InfologMessageList
        {
            get
            {
                return this.InfologMessageListField;
            }
            set
            {
                this.InfologMessageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType
        {
            get
            {
                return this.XppExceptionTypeField;
            }
            set
            {
                this.XppExceptionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object
    {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private KESSCNTServices.FaultMessage[] FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation
        {
            get
            {
                return this.DocumentOperationField;
            }
            set
            {
                this.DocumentOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCNTServices.FaultMessage[] FaultMessageArray
        {
            get
            {
                return this.FaultMessageArrayField;
            }
            set
            {
                this.FaultMessageArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation
        {
            get
            {
                return this.ServiceOperationField;
            }
            set
            {
                this.ServiceOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter
        {
            get
            {
                return this.ServiceOperationParameterField;
            }
            set
            {
                this.ServiceOperationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine
        {
            get
            {
                return this.XmlLineField;
            }
            set
            {
                this.XmlLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition
        {
            get
            {
                return this.XmlPositionField;
            }
            set
            {
                this.XmlPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object
    {
        
        private KESSCNTServices.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSCNTServices.InfologMessageType InfologMessageType
        {
            get
            {
                return this.InfologMessageTypeField;
            }
            set
            {
                this.InfologMessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="KESSCNTServices.KESSCNTService")]
    public interface KESSCNTService
    {
        
        // CODEGEN: Generating message contract since the wrapper name (KESSCNTServiceGetComplaintsListRequest) of message KESSCNTServiceGetComplaintsListRequest does not match the default value (getComplaintsList)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCNTService/getComplaintsList", ReplyAction="http://tempuri.org/KESSCNTService/getComplaintsListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSCNTServices.AifFault), Action="http://tempuri.org/KESSCNTService/getComplaintsListAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSCNTServices.KESSCNTServiceGetComplaintsListResponse getComplaintsList(KESSCNTServices.KESSCNTServiceGetComplaintsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCNTService/getComplaintsList", ReplyAction="http://tempuri.org/KESSCNTService/getComplaintsListResponse")]
        System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsListResponse> getComplaintsListAsync(KESSCNTServices.KESSCNTServiceGetComplaintsListRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSCNTServiceGetComplaintsByRecIdRequest) of message KESSCNTServiceGetComplaintsByRecIdRequest does not match the default value (getComplaintsByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCNTService/getComplaintsByRecId", ReplyAction="http://tempuri.org/KESSCNTService/getComplaintsByRecIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSCNTServices.AifFault), Action="http://tempuri.org/KESSCNTService/getComplaintsByRecIdAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSCNTServices.KESSCNTServiceGetComplaintsByRecIdResponse getComplaintsByRecId(KESSCNTServices.KESSCNTServiceGetComplaintsByRecIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCNTService/getComplaintsByRecId", ReplyAction="http://tempuri.org/KESSCNTService/getComplaintsByRecIdResponse")]
        System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsByRecIdResponse> getComplaintsByRecIdAsync(KESSCNTServices.KESSCNTServiceGetComplaintsByRecIdRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSCNTServiceGetComplaintsByEmplIdRequest) of message KESSCNTServiceGetComplaintsByEmplIdRequest does not match the default value (getComplaintsByEmplId)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCNTService/getComplaintsByEmplId", ReplyAction="http://tempuri.org/KESSCNTService/getComplaintsByEmplIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSCNTServices.AifFault), Action="http://tempuri.org/KESSCNTService/getComplaintsByEmplIdAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSCNTServices.KESSCNTServiceGetComplaintsByEmplIdResponse getComplaintsByEmplId(KESSCNTServices.KESSCNTServiceGetComplaintsByEmplIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCNTService/getComplaintsByEmplId", ReplyAction="http://tempuri.org/KESSCNTService/getComplaintsByEmplIdResponse")]
        System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsByEmplIdResponse> getComplaintsByEmplIdAsync(KESSCNTServices.KESSCNTServiceGetComplaintsByEmplIdRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSCNTServiceGetAgendaListRequest) of message KESSCNTServiceGetAgendaListRequest does not match the default value (getAgendaList)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCNTService/getAgendaList", ReplyAction="http://tempuri.org/KESSCNTService/getAgendaListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSCNTServices.AifFault), Action="http://tempuri.org/KESSCNTService/getAgendaListAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSCNTServices.KESSCNTServiceGetAgendaListResponse getAgendaList(KESSCNTServices.KESSCNTServiceGetAgendaListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCNTService/getAgendaList", ReplyAction="http://tempuri.org/KESSCNTService/getAgendaListResponse")]
        System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetAgendaListResponse> getAgendaListAsync(KESSCNTServices.KESSCNTServiceGetAgendaListRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSCNTServiceGetComplaintsListByStatusRequest) of message KESSCNTServiceGetComplaintsListByStatusRequest does not match the default value (getComplaintsListByStatus)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCNTService/getComplaintsListByStatus", ReplyAction="http://tempuri.org/KESSCNTService/getComplaintsListByStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSCNTServices.AifFault), Action="http://tempuri.org/KESSCNTService/getComplaintsListByStatusAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSCNTServices.KESSCNTServiceGetComplaintsListByStatusResponse getComplaintsListByStatus(KESSCNTServices.KESSCNTServiceGetComplaintsListByStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCNTService/getComplaintsListByStatus", ReplyAction="http://tempuri.org/KESSCNTService/getComplaintsListByStatusResponse")]
        System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsListByStatusResponse> getComplaintsListByStatusAsync(KESSCNTServices.KESSCNTServiceGetComplaintsListByStatusRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSCNTServiceGetComplaintsByIdRequest) of message KESSCNTServiceGetComplaintsByIdRequest does not match the default value (getComplaintsById)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCNTService/getComplaintsById", ReplyAction="http://tempuri.org/KESSCNTService/getComplaintsByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSCNTServices.AifFault), Action="http://tempuri.org/KESSCNTService/getComplaintsByIdAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSCNTServices.KESSCNTServiceGetComplaintsByIdResponse getComplaintsById(KESSCNTServices.KESSCNTServiceGetComplaintsByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSCNTService/getComplaintsById", ReplyAction="http://tempuri.org/KESSCNTService/getComplaintsByIdResponse")]
        System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsByIdResponse> getComplaintsByIdAsync(KESSCNTServices.KESSCNTServiceGetComplaintsByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCNTServiceGetComplaintsListRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCNTServiceGetComplaintsListRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSCNTServices.CallContext CallContext;
        
        public KESSCNTServiceGetComplaintsListRequest()
        {
        }
        
        public KESSCNTServiceGetComplaintsListRequest(KESSCNTServices.CallContext CallContext)
        {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCNTServiceGetComplaintsListResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCNTServiceGetComplaintsListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSCNTServices.ComplaintsTicket[] response;
        
        public KESSCNTServiceGetComplaintsListResponse()
        {
        }
        
        public KESSCNTServiceGetComplaintsListResponse(KESSCNTServices.ComplaintsTicket[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCNTServiceGetComplaintsByRecIdRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCNTServiceGetComplaintsByRecIdRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSCNTServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public long recId;
        
        public KESSCNTServiceGetComplaintsByRecIdRequest()
        {
        }
        
        public KESSCNTServiceGetComplaintsByRecIdRequest(KESSCNTServices.CallContext CallContext, long recId)
        {
            this.CallContext = CallContext;
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCNTServiceGetComplaintsByRecIdResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCNTServiceGetComplaintsByRecIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSCNTServices.ComplaintsTicket[] response;
        
        public KESSCNTServiceGetComplaintsByRecIdResponse()
        {
        }
        
        public KESSCNTServiceGetComplaintsByRecIdResponse(KESSCNTServices.ComplaintsTicket[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCNTServiceGetComplaintsByEmplIdRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCNTServiceGetComplaintsByEmplIdRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSCNTServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string EmplId;
        
        public KESSCNTServiceGetComplaintsByEmplIdRequest()
        {
        }
        
        public KESSCNTServiceGetComplaintsByEmplIdRequest(KESSCNTServices.CallContext CallContext, string EmplId)
        {
            this.CallContext = CallContext;
            this.EmplId = EmplId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCNTServiceGetComplaintsByEmplIdResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCNTServiceGetComplaintsByEmplIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSCNTServices.ComplaintsTicket[] response;
        
        public KESSCNTServiceGetComplaintsByEmplIdResponse()
        {
        }
        
        public KESSCNTServiceGetComplaintsByEmplIdResponse(KESSCNTServices.ComplaintsTicket[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCNTServiceGetAgendaListRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCNTServiceGetAgendaListRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSCNTServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.DateTime fromDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public System.DateTime toDate;
        
        public KESSCNTServiceGetAgendaListRequest()
        {
        }
        
        public KESSCNTServiceGetAgendaListRequest(KESSCNTServices.CallContext CallContext, System.DateTime fromDate, System.DateTime toDate)
        {
            this.CallContext = CallContext;
            this.fromDate = fromDate;
            this.toDate = toDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCNTServiceGetAgendaListResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCNTServiceGetAgendaListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSCNTServices.KESSAgenda[] response;
        
        public KESSCNTServiceGetAgendaListResponse()
        {
        }
        
        public KESSCNTServiceGetAgendaListResponse(KESSCNTServices.KESSAgenda[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCNTServiceGetComplaintsListByStatusRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCNTServiceGetComplaintsListByStatusRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSCNTServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSCNTServices.KESSTicketStatus status;
        
        public KESSCNTServiceGetComplaintsListByStatusRequest()
        {
        }
        
        public KESSCNTServiceGetComplaintsListByStatusRequest(KESSCNTServices.CallContext CallContext, KESSCNTServices.KESSTicketStatus status)
        {
            this.CallContext = CallContext;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCNTServiceGetComplaintsListByStatusResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCNTServiceGetComplaintsListByStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSCNTServices.ComplaintsTicket[] response;
        
        public KESSCNTServiceGetComplaintsListByStatusResponse()
        {
        }
        
        public KESSCNTServiceGetComplaintsListByStatusResponse(KESSCNTServices.ComplaintsTicket[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCNTServiceGetComplaintsByIdRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCNTServiceGetComplaintsByIdRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSCNTServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string complaintsId;
        
        public KESSCNTServiceGetComplaintsByIdRequest()
        {
        }
        
        public KESSCNTServiceGetComplaintsByIdRequest(KESSCNTServices.CallContext CallContext, string complaintsId)
        {
            this.CallContext = CallContext;
            this.complaintsId = complaintsId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSCNTServiceGetComplaintsByIdResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSCNTServiceGetComplaintsByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSCNTServices.ComplaintsTicket[] response;
        
        public KESSCNTServiceGetComplaintsByIdResponse()
        {
        }
        
        public KESSCNTServiceGetComplaintsByIdResponse(KESSCNTServices.ComplaintsTicket[] response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface KESSCNTServiceChannel : KESSCNTServices.KESSCNTService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class KESSCNTServiceClient : System.ServiceModel.ClientBase<KESSCNTServices.KESSCNTService>, KESSCNTServices.KESSCNTService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KESSCNTServiceClient() : 
                base(KESSCNTServiceClient.GetDefaultBinding(), KESSCNTServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_KESSCNTService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSCNTServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(KESSCNTServiceClient.GetBindingForEndpoint(endpointConfiguration), KESSCNTServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSCNTServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KESSCNTServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSCNTServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KESSCNTServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSCNTServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSCNTServices.KESSCNTServiceGetComplaintsListResponse KESSCNTServices.KESSCNTService.getComplaintsList(KESSCNTServices.KESSCNTServiceGetComplaintsListRequest request)
        {
            return base.Channel.getComplaintsList(request);
        }
        
        public KESSCNTServices.ComplaintsTicket[] getComplaintsList(KESSCNTServices.CallContext CallContext)
        {
            KESSCNTServices.KESSCNTServiceGetComplaintsListRequest inValue = new KESSCNTServices.KESSCNTServiceGetComplaintsListRequest();
            inValue.CallContext = CallContext;
            KESSCNTServices.KESSCNTServiceGetComplaintsListResponse retVal = ((KESSCNTServices.KESSCNTService)(this)).getComplaintsList(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsListResponse> KESSCNTServices.KESSCNTService.getComplaintsListAsync(KESSCNTServices.KESSCNTServiceGetComplaintsListRequest request)
        {
            return base.Channel.getComplaintsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsListResponse> getComplaintsListAsync(KESSCNTServices.CallContext CallContext)
        {
            KESSCNTServices.KESSCNTServiceGetComplaintsListRequest inValue = new KESSCNTServices.KESSCNTServiceGetComplaintsListRequest();
            inValue.CallContext = CallContext;
            return ((KESSCNTServices.KESSCNTService)(this)).getComplaintsListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSCNTServices.KESSCNTServiceGetComplaintsByRecIdResponse KESSCNTServices.KESSCNTService.getComplaintsByRecId(KESSCNTServices.KESSCNTServiceGetComplaintsByRecIdRequest request)
        {
            return base.Channel.getComplaintsByRecId(request);
        }
        
        public KESSCNTServices.ComplaintsTicket[] getComplaintsByRecId(KESSCNTServices.CallContext CallContext, long recId)
        {
            KESSCNTServices.KESSCNTServiceGetComplaintsByRecIdRequest inValue = new KESSCNTServices.KESSCNTServiceGetComplaintsByRecIdRequest();
            inValue.CallContext = CallContext;
            inValue.recId = recId;
            KESSCNTServices.KESSCNTServiceGetComplaintsByRecIdResponse retVal = ((KESSCNTServices.KESSCNTService)(this)).getComplaintsByRecId(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsByRecIdResponse> KESSCNTServices.KESSCNTService.getComplaintsByRecIdAsync(KESSCNTServices.KESSCNTServiceGetComplaintsByRecIdRequest request)
        {
            return base.Channel.getComplaintsByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsByRecIdResponse> getComplaintsByRecIdAsync(KESSCNTServices.CallContext CallContext, long recId)
        {
            KESSCNTServices.KESSCNTServiceGetComplaintsByRecIdRequest inValue = new KESSCNTServices.KESSCNTServiceGetComplaintsByRecIdRequest();
            inValue.CallContext = CallContext;
            inValue.recId = recId;
            return ((KESSCNTServices.KESSCNTService)(this)).getComplaintsByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSCNTServices.KESSCNTServiceGetComplaintsByEmplIdResponse KESSCNTServices.KESSCNTService.getComplaintsByEmplId(KESSCNTServices.KESSCNTServiceGetComplaintsByEmplIdRequest request)
        {
            return base.Channel.getComplaintsByEmplId(request);
        }
        
        public KESSCNTServices.ComplaintsTicket[] getComplaintsByEmplId(KESSCNTServices.CallContext CallContext, string EmplId)
        {
            KESSCNTServices.KESSCNTServiceGetComplaintsByEmplIdRequest inValue = new KESSCNTServices.KESSCNTServiceGetComplaintsByEmplIdRequest();
            inValue.CallContext = CallContext;
            inValue.EmplId = EmplId;
            KESSCNTServices.KESSCNTServiceGetComplaintsByEmplIdResponse retVal = ((KESSCNTServices.KESSCNTService)(this)).getComplaintsByEmplId(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsByEmplIdResponse> KESSCNTServices.KESSCNTService.getComplaintsByEmplIdAsync(KESSCNTServices.KESSCNTServiceGetComplaintsByEmplIdRequest request)
        {
            return base.Channel.getComplaintsByEmplIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsByEmplIdResponse> getComplaintsByEmplIdAsync(KESSCNTServices.CallContext CallContext, string EmplId)
        {
            KESSCNTServices.KESSCNTServiceGetComplaintsByEmplIdRequest inValue = new KESSCNTServices.KESSCNTServiceGetComplaintsByEmplIdRequest();
            inValue.CallContext = CallContext;
            inValue.EmplId = EmplId;
            return ((KESSCNTServices.KESSCNTService)(this)).getComplaintsByEmplIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSCNTServices.KESSCNTServiceGetAgendaListResponse KESSCNTServices.KESSCNTService.getAgendaList(KESSCNTServices.KESSCNTServiceGetAgendaListRequest request)
        {
            return base.Channel.getAgendaList(request);
        }
        
        public KESSCNTServices.KESSAgenda[] getAgendaList(KESSCNTServices.CallContext CallContext, System.DateTime fromDate, System.DateTime toDate)
        {
            KESSCNTServices.KESSCNTServiceGetAgendaListRequest inValue = new KESSCNTServices.KESSCNTServiceGetAgendaListRequest();
            inValue.CallContext = CallContext;
            inValue.fromDate = fromDate;
            inValue.toDate = toDate;
            KESSCNTServices.KESSCNTServiceGetAgendaListResponse retVal = ((KESSCNTServices.KESSCNTService)(this)).getAgendaList(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetAgendaListResponse> KESSCNTServices.KESSCNTService.getAgendaListAsync(KESSCNTServices.KESSCNTServiceGetAgendaListRequest request)
        {
            return base.Channel.getAgendaListAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetAgendaListResponse> getAgendaListAsync(KESSCNTServices.CallContext CallContext, System.DateTime fromDate, System.DateTime toDate)
        {
            KESSCNTServices.KESSCNTServiceGetAgendaListRequest inValue = new KESSCNTServices.KESSCNTServiceGetAgendaListRequest();
            inValue.CallContext = CallContext;
            inValue.fromDate = fromDate;
            inValue.toDate = toDate;
            return ((KESSCNTServices.KESSCNTService)(this)).getAgendaListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSCNTServices.KESSCNTServiceGetComplaintsListByStatusResponse KESSCNTServices.KESSCNTService.getComplaintsListByStatus(KESSCNTServices.KESSCNTServiceGetComplaintsListByStatusRequest request)
        {
            return base.Channel.getComplaintsListByStatus(request);
        }
        
        public KESSCNTServices.ComplaintsTicket[] getComplaintsListByStatus(KESSCNTServices.CallContext CallContext, KESSCNTServices.KESSTicketStatus status)
        {
            KESSCNTServices.KESSCNTServiceGetComplaintsListByStatusRequest inValue = new KESSCNTServices.KESSCNTServiceGetComplaintsListByStatusRequest();
            inValue.CallContext = CallContext;
            inValue.status = status;
            KESSCNTServices.KESSCNTServiceGetComplaintsListByStatusResponse retVal = ((KESSCNTServices.KESSCNTService)(this)).getComplaintsListByStatus(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsListByStatusResponse> KESSCNTServices.KESSCNTService.getComplaintsListByStatusAsync(KESSCNTServices.KESSCNTServiceGetComplaintsListByStatusRequest request)
        {
            return base.Channel.getComplaintsListByStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsListByStatusResponse> getComplaintsListByStatusAsync(KESSCNTServices.CallContext CallContext, KESSCNTServices.KESSTicketStatus status)
        {
            KESSCNTServices.KESSCNTServiceGetComplaintsListByStatusRequest inValue = new KESSCNTServices.KESSCNTServiceGetComplaintsListByStatusRequest();
            inValue.CallContext = CallContext;
            inValue.status = status;
            return ((KESSCNTServices.KESSCNTService)(this)).getComplaintsListByStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSCNTServices.KESSCNTServiceGetComplaintsByIdResponse KESSCNTServices.KESSCNTService.getComplaintsById(KESSCNTServices.KESSCNTServiceGetComplaintsByIdRequest request)
        {
            return base.Channel.getComplaintsById(request);
        }
        
        public KESSCNTServices.ComplaintsTicket[] getComplaintsById(KESSCNTServices.CallContext CallContext, string complaintsId)
        {
            KESSCNTServices.KESSCNTServiceGetComplaintsByIdRequest inValue = new KESSCNTServices.KESSCNTServiceGetComplaintsByIdRequest();
            inValue.CallContext = CallContext;
            inValue.complaintsId = complaintsId;
            KESSCNTServices.KESSCNTServiceGetComplaintsByIdResponse retVal = ((KESSCNTServices.KESSCNTService)(this)).getComplaintsById(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsByIdResponse> KESSCNTServices.KESSCNTService.getComplaintsByIdAsync(KESSCNTServices.KESSCNTServiceGetComplaintsByIdRequest request)
        {
            return base.Channel.getComplaintsByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSCNTServices.KESSCNTServiceGetComplaintsByIdResponse> getComplaintsByIdAsync(KESSCNTServices.CallContext CallContext, string complaintsId)
        {
            KESSCNTServices.KESSCNTServiceGetComplaintsByIdRequest inValue = new KESSCNTServices.KESSCNTServiceGetComplaintsByIdRequest();
            inValue.CallContext = CallContext;
            inValue.complaintsId = complaintsId;
            return ((KESSCNTServices.KESSCNTService)(this)).getComplaintsByIdAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_KESSCNTService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_KESSCNTService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://7.172.65.217:8202/DynamicsAx/Services/KESSCNTServices");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KESSCNTServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_KESSCNTService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KESSCNTServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_KESSCNTService);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_KESSCNTService,
        }
    }
}
