//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KESSLMServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object
    {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private string PartitionKeyField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser
        {
            get
            {
                return this.LogonAsUserField;
            }
            set
            {
                this.LogonAsUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LMLeaveCategory", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class LMLeaveCategory : KESSLMServices.XppObjectBase
    {
        
        private KESSLMServices.NoYes AnnualField;
        
        private string CategoryIdField;
        
        private KESSLMServices.NoYes CutiBesarField;
        
        private string DescriptionField;
        
        private KESSLMServices.NoYes MassiveField;
        
        private KESSLMServices.NoYes UnpaidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSLMServices.NoYes Annual
        {
            get
            {
                return this.AnnualField;
            }
            set
            {
                this.AnnualField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryId
        {
            get
            {
                return this.CategoryIdField;
            }
            set
            {
                this.CategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSLMServices.NoYes CutiBesar
        {
            get
            {
                return this.CutiBesarField;
            }
            set
            {
                this.CutiBesarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSLMServices.NoYes Massive
        {
            get
            {
                return this.MassiveField;
            }
            set
            {
                this.MassiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSLMServices.NoYes Unpaid
        {
            get
            {
                return this.UnpaidField;
            }
            set
            {
                this.UnpaidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSLMServices.LMLeaveEmployee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSLMServices.LMLeaveEmplSubordinate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSLMServices.LMLeaveEmplSubtitute))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSLMServices.LMLeaveMaintenance))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSLMServices.LMLeaveType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSLMServices.LMLeaveCategory))]
    public partial class XppObjectBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LMLeaveEmployee", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class LMLeaveEmployee : KESSLMServices.XppObjectBase
    {
        
        private KESSLMServices.LeaveApprovalStatus ApprovalStatusField;
        
        private string DescriptionField;
        
        private string DocumentPathField;
        
        private string EmplIdField;
        
        private string EmplNameField;
        
        private System.DateTime EndDateField;
        
        private int LeaveTypeField;
        
        private long RecIdField;
        
        private System.DateTime StartDateField;
        
        private string SubtituteEmplIdField;
        
        private string SubtituteEmplNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSLMServices.LeaveApprovalStatus ApprovalStatus
        {
            get
            {
                return this.ApprovalStatusField;
            }
            set
            {
                this.ApprovalStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentPath
        {
            get
            {
                return this.DocumentPathField;
            }
            set
            {
                this.DocumentPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplId
        {
            get
            {
                return this.EmplIdField;
            }
            set
            {
                this.EmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplName
        {
            get
            {
                return this.EmplNameField;
            }
            set
            {
                this.EmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeaveType
        {
            get
            {
                return this.LeaveTypeField;
            }
            set
            {
                this.LeaveTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubtituteEmplId
        {
            get
            {
                return this.SubtituteEmplIdField;
            }
            set
            {
                this.SubtituteEmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubtituteEmplName
        {
            get
            {
                return this.SubtituteEmplNameField;
            }
            set
            {
                this.SubtituteEmplNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LMLeaveEmplSubordinate", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class LMLeaveEmplSubordinate : KESSLMServices.XppObjectBase
    {
        
        private KESSLMServices.LeaveApprovalStatus ApprovalStatusField;
        
        private string DescriptionField;
        
        private string EmplIdField;
        
        private string EmplNameField;
        
        private System.DateTime EndDateField;
        
        private long RecIdField;
        
        private string ReportToEmplIdField;
        
        private string ReportToEmplNameField;
        
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSLMServices.LeaveApprovalStatus ApprovalStatus
        {
            get
            {
                return this.ApprovalStatusField;
            }
            set
            {
                this.ApprovalStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplId
        {
            get
            {
                return this.EmplIdField;
            }
            set
            {
                this.EmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplName
        {
            get
            {
                return this.EmplNameField;
            }
            set
            {
                this.EmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportToEmplId
        {
            get
            {
                return this.ReportToEmplIdField;
            }
            set
            {
                this.ReportToEmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportToEmplName
        {
            get
            {
                return this.ReportToEmplNameField;
            }
            set
            {
                this.ReportToEmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LMLeaveEmplSubtitute", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class LMLeaveEmplSubtitute : KESSLMServices.XppObjectBase
    {
        
        private long RecIdField;
        
        private string SubtituteEmplIdField;
        
        private string SubtituteEmplNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubtituteEmplId
        {
            get
            {
                return this.SubtituteEmplIdField;
            }
            set
            {
                this.SubtituteEmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubtituteEmplName
        {
            get
            {
                return this.SubtituteEmplNameField;
            }
            set
            {
                this.SubtituteEmplNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LMLeaveMaintenance", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class LMLeaveMaintenance : KESSLMServices.XppObjectBase
    {
        
        private KESSLMServices.NoYes AvailableField;
        
        private System.DateTime AvailableEndDateField;
        
        private System.DateTime AvailableStartDateField;
        
        private System.DateTime CFExpiredDateField;
        
        private string EmplIdField;
        
        private string EmplNameField;
        
        private KESSLMServices.NoYes IsClosedField;
        
        private int LeaveCFField;
        
        private string LeaveDescriptionField;
        
        private int LeaveRemainderField;
        
        private int LeaveRightsField;
        
        private int LeaveTypeField;
        
        private int LeaveYearField;
        
        private long RecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSLMServices.NoYes Available
        {
            get
            {
                return this.AvailableField;
            }
            set
            {
                this.AvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AvailableEndDate
        {
            get
            {
                return this.AvailableEndDateField;
            }
            set
            {
                this.AvailableEndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AvailableStartDate
        {
            get
            {
                return this.AvailableStartDateField;
            }
            set
            {
                this.AvailableStartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CFExpiredDate
        {
            get
            {
                return this.CFExpiredDateField;
            }
            set
            {
                this.CFExpiredDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplId
        {
            get
            {
                return this.EmplIdField;
            }
            set
            {
                this.EmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplName
        {
            get
            {
                return this.EmplNameField;
            }
            set
            {
                this.EmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSLMServices.NoYes IsClosed
        {
            get
            {
                return this.IsClosedField;
            }
            set
            {
                this.IsClosedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeaveCF
        {
            get
            {
                return this.LeaveCFField;
            }
            set
            {
                this.LeaveCFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeaveDescription
        {
            get
            {
                return this.LeaveDescriptionField;
            }
            set
            {
                this.LeaveDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeaveRemainder
        {
            get
            {
                return this.LeaveRemainderField;
            }
            set
            {
                this.LeaveRemainderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeaveRights
        {
            get
            {
                return this.LeaveRightsField;
            }
            set
            {
                this.LeaveRightsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeaveType
        {
            get
            {
                return this.LeaveTypeField;
            }
            set
            {
                this.LeaveTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeaveYear
        {
            get
            {
                return this.LeaveYearField;
            }
            set
            {
                this.LeaveYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LMLeaveType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class LMLeaveType : KESSLMServices.XppObjectBase
    {
        
        private string CategoryIdField;
        
        private KESSLMServices.KESSLeaveConsumeDay ConsumeDayField;
        
        private string DescriptionField;
        
        private System.DateTime EffectiveDateFromField;
        
        private System.DateTime EffectiveDateToField;
        
        private string EmplIdField;
        
        private string EmplNameField;
        
        private KESSLMServices.NoYes IsClosedField;
        
        private int LeaveRemainderField;
        
        private int MaxNumberOfLeaveField;
        
        private long RecIdField;
        
        private int TypeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryId
        {
            get
            {
                return this.CategoryIdField;
            }
            set
            {
                this.CategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSLMServices.KESSLeaveConsumeDay ConsumeDay
        {
            get
            {
                return this.ConsumeDayField;
            }
            set
            {
                this.ConsumeDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffectiveDateFrom
        {
            get
            {
                return this.EffectiveDateFromField;
            }
            set
            {
                this.EffectiveDateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffectiveDateTo
        {
            get
            {
                return this.EffectiveDateToField;
            }
            set
            {
                this.EffectiveDateToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplId
        {
            get
            {
                return this.EmplIdField;
            }
            set
            {
                this.EmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplName
        {
            get
            {
                return this.EmplNameField;
            }
            set
            {
                this.EmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSLMServices.NoYes IsClosed
        {
            get
            {
                return this.IsClosedField;
            }
            set
            {
                this.IsClosedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeaveRemainder
        {
            get
            {
                return this.LeaveRemainderField;
            }
            set
            {
                this.LeaveRemainderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNumberOfLeave
        {
            get
            {
                return this.MaxNumberOfLeaveField;
            }
            set
            {
                this.MaxNumberOfLeaveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeId
        {
            get
            {
                return this.TypeIdField;
            }
            set
            {
                this.TypeIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoYes", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    public enum NoYes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeaveApprovalStatus", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum LeaveApprovalStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Accept = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reject = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InReview = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSLeaveConsumeDay", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSLeaveConsumeDay : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CalendarDay = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkingDay = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object
    {
        
        private string CustomDetailXmlField;
        
        private KESSLMServices.FaultMessageList[] FaultMessageListArrayField;
        
        private KESSLMServices.InfologMessage[] InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml
        {
            get
            {
                return this.CustomDetailXmlField;
            }
            set
            {
                this.CustomDetailXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSLMServices.FaultMessageList[] FaultMessageListArray
        {
            get
            {
                return this.FaultMessageListArrayField;
            }
            set
            {
                this.FaultMessageListArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSLMServices.InfologMessage[] InfologMessageList
        {
            get
            {
                return this.InfologMessageListField;
            }
            set
            {
                this.InfologMessageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType
        {
            get
            {
                return this.XppExceptionTypeField;
            }
            set
            {
                this.XppExceptionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object
    {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private KESSLMServices.FaultMessage[] FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation
        {
            get
            {
                return this.DocumentOperationField;
            }
            set
            {
                this.DocumentOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSLMServices.FaultMessage[] FaultMessageArray
        {
            get
            {
                return this.FaultMessageArrayField;
            }
            set
            {
                this.FaultMessageArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation
        {
            get
            {
                return this.ServiceOperationField;
            }
            set
            {
                this.ServiceOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter
        {
            get
            {
                return this.ServiceOperationParameterField;
            }
            set
            {
                this.ServiceOperationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine
        {
            get
            {
                return this.XmlLineField;
            }
            set
            {
                this.XmlLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition
        {
            get
            {
                return this.XmlPositionField;
            }
            set
            {
                this.XmlPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object
    {
        
        private KESSLMServices.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSLMServices.InfologMessageType InfologMessageType
        {
            get
            {
                return this.InfologMessageTypeField;
            }
            set
            {
                this.InfologMessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="KESSLMServices.KESSLMService")]
    public interface KESSLMService
    {
        
        // CODEGEN: Generating message contract since the wrapper name (KESSLMServiceGetLMLeaveCategoryRequest) of message KESSLMServiceGetLMLeaveCategoryRequest does not match the default value (getLMLeaveCategory)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSLMService/getLMLeaveCategory", ReplyAction="http://tempuri.org/KESSLMService/getLMLeaveCategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSLMServices.AifFault), Action="http://tempuri.org/KESSLMService/getLMLeaveCategoryAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSLMServices.KESSLMServiceGetLMLeaveCategoryResponse getLMLeaveCategory(KESSLMServices.KESSLMServiceGetLMLeaveCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSLMService/getLMLeaveCategory", ReplyAction="http://tempuri.org/KESSLMService/getLMLeaveCategoryResponse")]
        System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveCategoryResponse> getLMLeaveCategoryAsync(KESSLMServices.KESSLMServiceGetLMLeaveCategoryRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSLMServiceGetLMLeaveEmplSubtituteRequest) of message KESSLMServiceGetLMLeaveEmplSubtituteRequest does not match the default value (getLMLeaveEmplSubtitute)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSLMService/getLMLeaveEmplSubtitute", ReplyAction="http://tempuri.org/KESSLMService/getLMLeaveEmplSubtituteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSLMServices.AifFault), Action="http://tempuri.org/KESSLMService/getLMLeaveEmplSubtituteAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSLMServices.KESSLMServiceGetLMLeaveEmplSubtituteResponse getLMLeaveEmplSubtitute(KESSLMServices.KESSLMServiceGetLMLeaveEmplSubtituteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSLMService/getLMLeaveEmplSubtitute", ReplyAction="http://tempuri.org/KESSLMService/getLMLeaveEmplSubtituteResponse")]
        System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveEmplSubtituteResponse> getLMLeaveEmplSubtituteAsync(KESSLMServices.KESSLMServiceGetLMLeaveEmplSubtituteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSLMServiceGetLMLeaveMaintenanceRequest) of message KESSLMServiceGetLMLeaveMaintenanceRequest does not match the default value (getLMLeaveMaintenance)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSLMService/getLMLeaveMaintenance", ReplyAction="http://tempuri.org/KESSLMService/getLMLeaveMaintenanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSLMServices.AifFault), Action="http://tempuri.org/KESSLMService/getLMLeaveMaintenanceAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSLMServices.KESSLMServiceGetLMLeaveMaintenanceResponse getLMLeaveMaintenance(KESSLMServices.KESSLMServiceGetLMLeaveMaintenanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSLMService/getLMLeaveMaintenance", ReplyAction="http://tempuri.org/KESSLMService/getLMLeaveMaintenanceResponse")]
        System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveMaintenanceResponse> getLMLeaveMaintenanceAsync(KESSLMServices.KESSLMServiceGetLMLeaveMaintenanceRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSLMServiceGetLMLeaveEmplSubordinateRequest) of message KESSLMServiceGetLMLeaveEmplSubordinateRequest does not match the default value (getLMLeaveEmplSubordinate)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSLMService/getLMLeaveEmplSubordinate", ReplyAction="http://tempuri.org/KESSLMService/getLMLeaveEmplSubordinateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSLMServices.AifFault), Action="http://tempuri.org/KESSLMService/getLMLeaveEmplSubordinateAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSLMServices.KESSLMServiceGetLMLeaveEmplSubordinateResponse getLMLeaveEmplSubordinate(KESSLMServices.KESSLMServiceGetLMLeaveEmplSubordinateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSLMService/getLMLeaveEmplSubordinate", ReplyAction="http://tempuri.org/KESSLMService/getLMLeaveEmplSubordinateResponse")]
        System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveEmplSubordinateResponse> getLMLeaveEmplSubordinateAsync(KESSLMServices.KESSLMServiceGetLMLeaveEmplSubordinateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSLMServiceGetLMLeaveEmployeeRequest) of message KESSLMServiceGetLMLeaveEmployeeRequest does not match the default value (getLMLeaveEmployee)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSLMService/getLMLeaveEmployee", ReplyAction="http://tempuri.org/KESSLMService/getLMLeaveEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSLMServices.AifFault), Action="http://tempuri.org/KESSLMService/getLMLeaveEmployeeAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSLMServices.KESSLMServiceGetLMLeaveEmployeeResponse getLMLeaveEmployee(KESSLMServices.KESSLMServiceGetLMLeaveEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSLMService/getLMLeaveEmployee", ReplyAction="http://tempuri.org/KESSLMService/getLMLeaveEmployeeResponse")]
        System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveEmployeeResponse> getLMLeaveEmployeeAsync(KESSLMServices.KESSLMServiceGetLMLeaveEmployeeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSLMServiceGetLMLeaveTypeRequest) of message KESSLMServiceGetLMLeaveTypeRequest does not match the default value (getLMLeaveType)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSLMService/getLMLeaveType", ReplyAction="http://tempuri.org/KESSLMService/getLMLeaveTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSLMServices.AifFault), Action="http://tempuri.org/KESSLMService/getLMLeaveTypeAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSLMServices.KESSLMServiceGetLMLeaveTypeResponse getLMLeaveType(KESSLMServices.KESSLMServiceGetLMLeaveTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSLMService/getLMLeaveType", ReplyAction="http://tempuri.org/KESSLMService/getLMLeaveTypeResponse")]
        System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveTypeResponse> getLMLeaveTypeAsync(KESSLMServices.KESSLMServiceGetLMLeaveTypeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSLMServiceGetLMLeaveCategoryRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSLMServiceGetLMLeaveCategoryRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSLMServices.CallContext CallContext;
        
        public KESSLMServiceGetLMLeaveCategoryRequest()
        {
        }
        
        public KESSLMServiceGetLMLeaveCategoryRequest(KESSLMServices.CallContext CallContext)
        {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSLMServiceGetLMLeaveCategoryResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSLMServiceGetLMLeaveCategoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSLMServices.LMLeaveCategory[] response;
        
        public KESSLMServiceGetLMLeaveCategoryResponse()
        {
        }
        
        public KESSLMServiceGetLMLeaveCategoryResponse(KESSLMServices.LMLeaveCategory[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSLMServiceGetLMLeaveEmplSubtituteRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSLMServiceGetLMLeaveEmplSubtituteRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSLMServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _emplId;
        
        public KESSLMServiceGetLMLeaveEmplSubtituteRequest()
        {
        }
        
        public KESSLMServiceGetLMLeaveEmplSubtituteRequest(KESSLMServices.CallContext CallContext, string _emplId)
        {
            this.CallContext = CallContext;
            this._emplId = _emplId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSLMServiceGetLMLeaveEmplSubtituteResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSLMServiceGetLMLeaveEmplSubtituteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSLMServices.LMLeaveEmplSubtitute[] response;
        
        public KESSLMServiceGetLMLeaveEmplSubtituteResponse()
        {
        }
        
        public KESSLMServiceGetLMLeaveEmplSubtituteResponse(KESSLMServices.LMLeaveEmplSubtitute[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSLMServiceGetLMLeaveMaintenanceRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSLMServiceGetLMLeaveMaintenanceRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSLMServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _emplId;
        
        public KESSLMServiceGetLMLeaveMaintenanceRequest()
        {
        }
        
        public KESSLMServiceGetLMLeaveMaintenanceRequest(KESSLMServices.CallContext CallContext, string _emplId)
        {
            this.CallContext = CallContext;
            this._emplId = _emplId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSLMServiceGetLMLeaveMaintenanceResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSLMServiceGetLMLeaveMaintenanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSLMServices.LMLeaveMaintenance[] response;
        
        public KESSLMServiceGetLMLeaveMaintenanceResponse()
        {
        }
        
        public KESSLMServiceGetLMLeaveMaintenanceResponse(KESSLMServices.LMLeaveMaintenance[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSLMServiceGetLMLeaveEmplSubordinateRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSLMServiceGetLMLeaveEmplSubordinateRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSLMServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _emplId;
        
        public KESSLMServiceGetLMLeaveEmplSubordinateRequest()
        {
        }
        
        public KESSLMServiceGetLMLeaveEmplSubordinateRequest(KESSLMServices.CallContext CallContext, string _emplId)
        {
            this.CallContext = CallContext;
            this._emplId = _emplId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSLMServiceGetLMLeaveEmplSubordinateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSLMServiceGetLMLeaveEmplSubordinateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSLMServices.LMLeaveEmplSubordinate[] response;
        
        public KESSLMServiceGetLMLeaveEmplSubordinateResponse()
        {
        }
        
        public KESSLMServiceGetLMLeaveEmplSubordinateResponse(KESSLMServices.LMLeaveEmplSubordinate[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSLMServiceGetLMLeaveEmployeeRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSLMServiceGetLMLeaveEmployeeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSLMServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _emplId;
        
        public KESSLMServiceGetLMLeaveEmployeeRequest()
        {
        }
        
        public KESSLMServiceGetLMLeaveEmployeeRequest(KESSLMServices.CallContext CallContext, string _emplId)
        {
            this.CallContext = CallContext;
            this._emplId = _emplId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSLMServiceGetLMLeaveEmployeeResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSLMServiceGetLMLeaveEmployeeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSLMServices.LMLeaveEmployee[] response;
        
        public KESSLMServiceGetLMLeaveEmployeeResponse()
        {
        }
        
        public KESSLMServiceGetLMLeaveEmployeeResponse(KESSLMServices.LMLeaveEmployee[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSLMServiceGetLMLeaveTypeRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSLMServiceGetLMLeaveTypeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSLMServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _emplId;
        
        public KESSLMServiceGetLMLeaveTypeRequest()
        {
        }
        
        public KESSLMServiceGetLMLeaveTypeRequest(KESSLMServices.CallContext CallContext, string _emplId)
        {
            this.CallContext = CallContext;
            this._emplId = _emplId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSLMServiceGetLMLeaveTypeResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSLMServiceGetLMLeaveTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSLMServices.LMLeaveType[] response;
        
        public KESSLMServiceGetLMLeaveTypeResponse()
        {
        }
        
        public KESSLMServiceGetLMLeaveTypeResponse(KESSLMServices.LMLeaveType[] response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface KESSLMServiceChannel : KESSLMServices.KESSLMService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class KESSLMServiceClient : System.ServiceModel.ClientBase<KESSLMServices.KESSLMService>, KESSLMServices.KESSLMService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KESSLMServiceClient() : 
                base(KESSLMServiceClient.GetDefaultBinding(), KESSLMServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_KESSLMService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSLMServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(KESSLMServiceClient.GetBindingForEndpoint(endpointConfiguration), KESSLMServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSLMServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KESSLMServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSLMServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KESSLMServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSLMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSLMServices.KESSLMServiceGetLMLeaveCategoryResponse KESSLMServices.KESSLMService.getLMLeaveCategory(KESSLMServices.KESSLMServiceGetLMLeaveCategoryRequest request)
        {
            return base.Channel.getLMLeaveCategory(request);
        }
        
        public KESSLMServices.LMLeaveCategory[] getLMLeaveCategory(KESSLMServices.CallContext CallContext)
        {
            KESSLMServices.KESSLMServiceGetLMLeaveCategoryRequest inValue = new KESSLMServices.KESSLMServiceGetLMLeaveCategoryRequest();
            inValue.CallContext = CallContext;
            KESSLMServices.KESSLMServiceGetLMLeaveCategoryResponse retVal = ((KESSLMServices.KESSLMService)(this)).getLMLeaveCategory(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveCategoryResponse> KESSLMServices.KESSLMService.getLMLeaveCategoryAsync(KESSLMServices.KESSLMServiceGetLMLeaveCategoryRequest request)
        {
            return base.Channel.getLMLeaveCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveCategoryResponse> getLMLeaveCategoryAsync(KESSLMServices.CallContext CallContext)
        {
            KESSLMServices.KESSLMServiceGetLMLeaveCategoryRequest inValue = new KESSLMServices.KESSLMServiceGetLMLeaveCategoryRequest();
            inValue.CallContext = CallContext;
            return ((KESSLMServices.KESSLMService)(this)).getLMLeaveCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSLMServices.KESSLMServiceGetLMLeaveEmplSubtituteResponse KESSLMServices.KESSLMService.getLMLeaveEmplSubtitute(KESSLMServices.KESSLMServiceGetLMLeaveEmplSubtituteRequest request)
        {
            return base.Channel.getLMLeaveEmplSubtitute(request);
        }
        
        public KESSLMServices.LMLeaveEmplSubtitute[] getLMLeaveEmplSubtitute(KESSLMServices.CallContext CallContext, string _emplId)
        {
            KESSLMServices.KESSLMServiceGetLMLeaveEmplSubtituteRequest inValue = new KESSLMServices.KESSLMServiceGetLMLeaveEmplSubtituteRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            KESSLMServices.KESSLMServiceGetLMLeaveEmplSubtituteResponse retVal = ((KESSLMServices.KESSLMService)(this)).getLMLeaveEmplSubtitute(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveEmplSubtituteResponse> KESSLMServices.KESSLMService.getLMLeaveEmplSubtituteAsync(KESSLMServices.KESSLMServiceGetLMLeaveEmplSubtituteRequest request)
        {
            return base.Channel.getLMLeaveEmplSubtituteAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveEmplSubtituteResponse> getLMLeaveEmplSubtituteAsync(KESSLMServices.CallContext CallContext, string _emplId)
        {
            KESSLMServices.KESSLMServiceGetLMLeaveEmplSubtituteRequest inValue = new KESSLMServices.KESSLMServiceGetLMLeaveEmplSubtituteRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            return ((KESSLMServices.KESSLMService)(this)).getLMLeaveEmplSubtituteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSLMServices.KESSLMServiceGetLMLeaveMaintenanceResponse KESSLMServices.KESSLMService.getLMLeaveMaintenance(KESSLMServices.KESSLMServiceGetLMLeaveMaintenanceRequest request)
        {
            return base.Channel.getLMLeaveMaintenance(request);
        }
        
        public KESSLMServices.LMLeaveMaintenance[] getLMLeaveMaintenance(KESSLMServices.CallContext CallContext, string _emplId)
        {
            KESSLMServices.KESSLMServiceGetLMLeaveMaintenanceRequest inValue = new KESSLMServices.KESSLMServiceGetLMLeaveMaintenanceRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            KESSLMServices.KESSLMServiceGetLMLeaveMaintenanceResponse retVal = ((KESSLMServices.KESSLMService)(this)).getLMLeaveMaintenance(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveMaintenanceResponse> KESSLMServices.KESSLMService.getLMLeaveMaintenanceAsync(KESSLMServices.KESSLMServiceGetLMLeaveMaintenanceRequest request)
        {
            return base.Channel.getLMLeaveMaintenanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveMaintenanceResponse> getLMLeaveMaintenanceAsync(KESSLMServices.CallContext CallContext, string _emplId)
        {
            KESSLMServices.KESSLMServiceGetLMLeaveMaintenanceRequest inValue = new KESSLMServices.KESSLMServiceGetLMLeaveMaintenanceRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            return ((KESSLMServices.KESSLMService)(this)).getLMLeaveMaintenanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSLMServices.KESSLMServiceGetLMLeaveEmplSubordinateResponse KESSLMServices.KESSLMService.getLMLeaveEmplSubordinate(KESSLMServices.KESSLMServiceGetLMLeaveEmplSubordinateRequest request)
        {
            return base.Channel.getLMLeaveEmplSubordinate(request);
        }
        
        public KESSLMServices.LMLeaveEmplSubordinate[] getLMLeaveEmplSubordinate(KESSLMServices.CallContext CallContext, string _emplId)
        {
            KESSLMServices.KESSLMServiceGetLMLeaveEmplSubordinateRequest inValue = new KESSLMServices.KESSLMServiceGetLMLeaveEmplSubordinateRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            KESSLMServices.KESSLMServiceGetLMLeaveEmplSubordinateResponse retVal = ((KESSLMServices.KESSLMService)(this)).getLMLeaveEmplSubordinate(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveEmplSubordinateResponse> KESSLMServices.KESSLMService.getLMLeaveEmplSubordinateAsync(KESSLMServices.KESSLMServiceGetLMLeaveEmplSubordinateRequest request)
        {
            return base.Channel.getLMLeaveEmplSubordinateAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveEmplSubordinateResponse> getLMLeaveEmplSubordinateAsync(KESSLMServices.CallContext CallContext, string _emplId)
        {
            KESSLMServices.KESSLMServiceGetLMLeaveEmplSubordinateRequest inValue = new KESSLMServices.KESSLMServiceGetLMLeaveEmplSubordinateRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            return ((KESSLMServices.KESSLMService)(this)).getLMLeaveEmplSubordinateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSLMServices.KESSLMServiceGetLMLeaveEmployeeResponse KESSLMServices.KESSLMService.getLMLeaveEmployee(KESSLMServices.KESSLMServiceGetLMLeaveEmployeeRequest request)
        {
            return base.Channel.getLMLeaveEmployee(request);
        }
        
        public KESSLMServices.LMLeaveEmployee[] getLMLeaveEmployee(KESSLMServices.CallContext CallContext, string _emplId)
        {
            KESSLMServices.KESSLMServiceGetLMLeaveEmployeeRequest inValue = new KESSLMServices.KESSLMServiceGetLMLeaveEmployeeRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            KESSLMServices.KESSLMServiceGetLMLeaveEmployeeResponse retVal = ((KESSLMServices.KESSLMService)(this)).getLMLeaveEmployee(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveEmployeeResponse> KESSLMServices.KESSLMService.getLMLeaveEmployeeAsync(KESSLMServices.KESSLMServiceGetLMLeaveEmployeeRequest request)
        {
            return base.Channel.getLMLeaveEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveEmployeeResponse> getLMLeaveEmployeeAsync(KESSLMServices.CallContext CallContext, string _emplId)
        {
            KESSLMServices.KESSLMServiceGetLMLeaveEmployeeRequest inValue = new KESSLMServices.KESSLMServiceGetLMLeaveEmployeeRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            return ((KESSLMServices.KESSLMService)(this)).getLMLeaveEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSLMServices.KESSLMServiceGetLMLeaveTypeResponse KESSLMServices.KESSLMService.getLMLeaveType(KESSLMServices.KESSLMServiceGetLMLeaveTypeRequest request)
        {
            return base.Channel.getLMLeaveType(request);
        }
        
        public KESSLMServices.LMLeaveType[] getLMLeaveType(KESSLMServices.CallContext CallContext, string _emplId)
        {
            KESSLMServices.KESSLMServiceGetLMLeaveTypeRequest inValue = new KESSLMServices.KESSLMServiceGetLMLeaveTypeRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            KESSLMServices.KESSLMServiceGetLMLeaveTypeResponse retVal = ((KESSLMServices.KESSLMService)(this)).getLMLeaveType(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveTypeResponse> KESSLMServices.KESSLMService.getLMLeaveTypeAsync(KESSLMServices.KESSLMServiceGetLMLeaveTypeRequest request)
        {
            return base.Channel.getLMLeaveTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSLMServices.KESSLMServiceGetLMLeaveTypeResponse> getLMLeaveTypeAsync(KESSLMServices.CallContext CallContext, string _emplId)
        {
            KESSLMServices.KESSLMServiceGetLMLeaveTypeRequest inValue = new KESSLMServices.KESSLMServiceGetLMLeaveTypeRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            return ((KESSLMServices.KESSLMService)(this)).getLMLeaveTypeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_KESSLMService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_KESSLMService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://tpsaxappx:8202/DynamicsAx/Services/KESSLMServices");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KESSLMServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_KESSLMService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KESSLMServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_KESSLMService);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_KESSLMService,
        }
    }
}
