//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KESSPYServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object
    {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private string PartitionKeyField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser
        {
            get
            {
                return this.LogonAsUserField;
            }
            set
            {
                this.LogonAsUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PYPayrollCalculation", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class PYPayrollCalculation : KESSPYServices.XppObjectBase
    {
        
        private string EmplIdField;
        
        private string EmplNameField;
        
        private decimal NettoSalaryField;
        
        private string PayslipReportPathField;
        
        private int PeriodMonthField;
        
        private int PeriodYearField;
        
        private string ProcessIdField;
        
        private KESSPYServices.PyCycleTime ProcessTypeField;
        
        private long RecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplId
        {
            get
            {
                return this.EmplIdField;
            }
            set
            {
                this.EmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplName
        {
            get
            {
                return this.EmplNameField;
            }
            set
            {
                this.EmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NettoSalary
        {
            get
            {
                return this.NettoSalaryField;
            }
            set
            {
                this.NettoSalaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayslipReportPath
        {
            get
            {
                return this.PayslipReportPathField;
            }
            set
            {
                this.PayslipReportPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodMonth
        {
            get
            {
                return this.PeriodMonthField;
            }
            set
            {
                this.PeriodMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodYear
        {
            get
            {
                return this.PeriodYearField;
            }
            set
            {
                this.PeriodYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessId
        {
            get
            {
                return this.ProcessIdField;
            }
            set
            {
                this.ProcessIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSPYServices.PyCycleTime ProcessType
        {
            get
            {
                return this.ProcessTypeField;
            }
            set
            {
                this.ProcessTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSPYServices.PyPeriod))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSPYServices.PYPayrollCalculation))]
    public partial class XppObjectBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PyPeriod", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class PyPeriod : KESSPYServices.XppObjectBase
    {
        
        private KESSPYServices.NoYes ClosedField;
        
        private string DescriptionField;
        
        private System.DateTime EndDateField;
        
        private string PeriodIdField;
        
        private int PeriodNumberField;
        
        private string PeriodTypeIdField;
        
        private KESSPYServices.NoYes RampungField;
        
        private long RecIdField;
        
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSPYServices.NoYes Closed
        {
            get
            {
                return this.ClosedField;
            }
            set
            {
                this.ClosedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PeriodId
        {
            get
            {
                return this.PeriodIdField;
            }
            set
            {
                this.PeriodIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodNumber
        {
            get
            {
                return this.PeriodNumberField;
            }
            set
            {
                this.PeriodNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PeriodTypeId
        {
            get
            {
                return this.PeriodTypeIdField;
            }
            set
            {
                this.PeriodTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSPYServices.NoYes Rampung
        {
            get
            {
                return this.RampungField;
            }
            set
            {
                this.RampungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PyCycleTime", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum PyCycleTime : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Salary = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Premi = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VMT = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Overtime = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transport = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reward = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Shift = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bonus = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pendidikan = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CutiPanjang = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        THR = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CutiTahunan = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CutiBesar = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Housing = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        THM = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        T_UM = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BonusAkhirTahun = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRPL_PERIODIC = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BonusTambahan = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kinerja = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Purna_Bhakti = 21,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoYes", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    public enum NoYes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object
    {
        
        private string CustomDetailXmlField;
        
        private KESSPYServices.FaultMessageList[] FaultMessageListArrayField;
        
        private KESSPYServices.InfologMessage[] InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml
        {
            get
            {
                return this.CustomDetailXmlField;
            }
            set
            {
                this.CustomDetailXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSPYServices.FaultMessageList[] FaultMessageListArray
        {
            get
            {
                return this.FaultMessageListArrayField;
            }
            set
            {
                this.FaultMessageListArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSPYServices.InfologMessage[] InfologMessageList
        {
            get
            {
                return this.InfologMessageListField;
            }
            set
            {
                this.InfologMessageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType
        {
            get
            {
                return this.XppExceptionTypeField;
            }
            set
            {
                this.XppExceptionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object
    {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private KESSPYServices.FaultMessage[] FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation
        {
            get
            {
                return this.DocumentOperationField;
            }
            set
            {
                this.DocumentOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSPYServices.FaultMessage[] FaultMessageArray
        {
            get
            {
                return this.FaultMessageArrayField;
            }
            set
            {
                this.FaultMessageArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation
        {
            get
            {
                return this.ServiceOperationField;
            }
            set
            {
                this.ServiceOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter
        {
            get
            {
                return this.ServiceOperationParameterField;
            }
            set
            {
                this.ServiceOperationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine
        {
            get
            {
                return this.XmlLineField;
            }
            set
            {
                this.XmlLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition
        {
            get
            {
                return this.XmlPositionField;
            }
            set
            {
                this.XmlPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object
    {
        
        private KESSPYServices.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSPYServices.InfologMessageType InfologMessageType
        {
            get
            {
                return this.InfologMessageTypeField;
            }
            set
            {
                this.InfologMessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="KESSPYServices.KESSPYService")]
    public interface KESSPYService
    {
        
        // CODEGEN: Generating message contract since the wrapper name (KESSPYServiceGetPYPayrollCalcLoanRequest) of message KESSPYServiceGetPYPayrollCalcLoanRequest does not match the default value (getPYPayrollCalcLoan)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSPYService/getPYPayrollCalcLoan", ReplyAction="http://tempuri.org/KESSPYService/getPYPayrollCalcLoanResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSPYServices.AifFault), Action="http://tempuri.org/KESSPYService/getPYPayrollCalcLoanAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSPYServices.KESSPYServiceGetPYPayrollCalcLoanResponse getPYPayrollCalcLoan(KESSPYServices.KESSPYServiceGetPYPayrollCalcLoanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSPYService/getPYPayrollCalcLoan", ReplyAction="http://tempuri.org/KESSPYService/getPYPayrollCalcLoanResponse")]
        System.Threading.Tasks.Task<KESSPYServices.KESSPYServiceGetPYPayrollCalcLoanResponse> getPYPayrollCalcLoanAsync(KESSPYServices.KESSPYServiceGetPYPayrollCalcLoanRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSPYServiceGetPYPayrollCalculationRequest) of message KESSPYServiceGetPYPayrollCalculationRequest does not match the default value (getPYPayrollCalculation)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSPYService/getPYPayrollCalculation", ReplyAction="http://tempuri.org/KESSPYService/getPYPayrollCalculationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSPYServices.AifFault), Action="http://tempuri.org/KESSPYService/getPYPayrollCalculationAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSPYServices.KESSPYServiceGetPYPayrollCalculationResponse getPYPayrollCalculation(KESSPYServices.KESSPYServiceGetPYPayrollCalculationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSPYService/getPYPayrollCalculation", ReplyAction="http://tempuri.org/KESSPYService/getPYPayrollCalculationResponse")]
        System.Threading.Tasks.Task<KESSPYServices.KESSPYServiceGetPYPayrollCalculationResponse> getPYPayrollCalculationAsync(KESSPYServices.KESSPYServiceGetPYPayrollCalculationRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSPYServiceGetPyPeriodRequest) of message KESSPYServiceGetPyPeriodRequest does not match the default value (getPyPeriod)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSPYService/getPyPeriod", ReplyAction="http://tempuri.org/KESSPYService/getPyPeriodResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSPYServices.AifFault), Action="http://tempuri.org/KESSPYService/getPyPeriodAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSPYServices.KESSPYServiceGetPyPeriodResponse getPyPeriod(KESSPYServices.KESSPYServiceGetPyPeriodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSPYService/getPyPeriod", ReplyAction="http://tempuri.org/KESSPYService/getPyPeriodResponse")]
        System.Threading.Tasks.Task<KESSPYServices.KESSPYServiceGetPyPeriodResponse> getPyPeriodAsync(KESSPYServices.KESSPYServiceGetPyPeriodRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (KESSPYServiceNewPYPayslipReportRequest) of message KESSPYServiceNewPYPayslipReportRequest does not match the default value (newPYPayslipReport)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSPYService/newPYPayslipReport", ReplyAction="http://tempuri.org/KESSPYService/newPYPayslipReportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSPYServices.AifFault), Action="http://tempuri.org/KESSPYService/newPYPayslipReportAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSPYServices.KESSPYServiceNewPYPayslipReportResponse newPYPayslipReport(KESSPYServices.KESSPYServiceNewPYPayslipReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSPYService/newPYPayslipReport", ReplyAction="http://tempuri.org/KESSPYService/newPYPayslipReportResponse")]
        System.Threading.Tasks.Task<KESSPYServices.KESSPYServiceNewPYPayslipReportResponse> newPYPayslipReportAsync(KESSPYServices.KESSPYServiceNewPYPayslipReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSPYServiceGetPYPayrollCalcLoanRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSPYServiceGetPYPayrollCalcLoanRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSPYServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _emplId;
        
        public KESSPYServiceGetPYPayrollCalcLoanRequest()
        {
        }
        
        public KESSPYServiceGetPYPayrollCalcLoanRequest(KESSPYServices.CallContext CallContext, string _emplId)
        {
            this.CallContext = CallContext;
            this._emplId = _emplId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSPYServiceGetPYPayrollCalcLoanResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSPYServiceGetPYPayrollCalcLoanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSPYServices.PYPayrollCalculation[] response;
        
        public KESSPYServiceGetPYPayrollCalcLoanResponse()
        {
        }
        
        public KESSPYServiceGetPYPayrollCalcLoanResponse(KESSPYServices.PYPayrollCalculation[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSPYServiceGetPYPayrollCalculationRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSPYServiceGetPYPayrollCalculationRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSPYServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _emplId;
        
        public KESSPYServiceGetPYPayrollCalculationRequest()
        {
        }
        
        public KESSPYServiceGetPYPayrollCalculationRequest(KESSPYServices.CallContext CallContext, string _emplId)
        {
            this.CallContext = CallContext;
            this._emplId = _emplId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSPYServiceGetPYPayrollCalculationResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSPYServiceGetPYPayrollCalculationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSPYServices.PYPayrollCalculation[] response;
        
        public KESSPYServiceGetPYPayrollCalculationResponse()
        {
        }
        
        public KESSPYServiceGetPYPayrollCalculationResponse(KESSPYServices.PYPayrollCalculation[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSPYServiceGetPyPeriodRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSPYServiceGetPyPeriodRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSPYServices.CallContext CallContext;
        
        public KESSPYServiceGetPyPeriodRequest()
        {
        }
        
        public KESSPYServiceGetPyPeriodRequest(KESSPYServices.CallContext CallContext)
        {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSPYServiceGetPyPeriodResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSPYServiceGetPyPeriodResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSPYServices.PyPeriod[] response;
        
        public KESSPYServiceGetPyPeriodResponse()
        {
        }
        
        public KESSPYServiceGetPyPeriodResponse(KESSPYServices.PyPeriod[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSPYServiceNewPYPayslipReportRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSPYServiceNewPYPayslipReportRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSPYServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSPYServices.PYPayrollCalculation _payrollCalculationModel;
        
        public KESSPYServiceNewPYPayslipReportRequest()
        {
        }
        
        public KESSPYServiceNewPYPayslipReportRequest(KESSPYServices.CallContext CallContext, KESSPYServices.PYPayrollCalculation _payrollCalculationModel)
        {
            this.CallContext = CallContext;
            this._payrollCalculationModel = _payrollCalculationModel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSPYServiceNewPYPayslipReportResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSPYServiceNewPYPayslipReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public KESSPYServiceNewPYPayslipReportResponse()
        {
        }
        
        public KESSPYServiceNewPYPayslipReportResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface KESSPYServiceChannel : KESSPYServices.KESSPYService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class KESSPYServiceClient : System.ServiceModel.ClientBase<KESSPYServices.KESSPYService>, KESSPYServices.KESSPYService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KESSPYServiceClient() : 
                base(KESSPYServiceClient.GetDefaultBinding(), KESSPYServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_KESSPYService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSPYServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(KESSPYServiceClient.GetBindingForEndpoint(endpointConfiguration), KESSPYServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSPYServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KESSPYServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSPYServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KESSPYServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSPYServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSPYServices.KESSPYServiceGetPYPayrollCalcLoanResponse KESSPYServices.KESSPYService.getPYPayrollCalcLoan(KESSPYServices.KESSPYServiceGetPYPayrollCalcLoanRequest request)
        {
            return base.Channel.getPYPayrollCalcLoan(request);
        }
        
        public KESSPYServices.PYPayrollCalculation[] getPYPayrollCalcLoan(KESSPYServices.CallContext CallContext, string _emplId)
        {
            KESSPYServices.KESSPYServiceGetPYPayrollCalcLoanRequest inValue = new KESSPYServices.KESSPYServiceGetPYPayrollCalcLoanRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            KESSPYServices.KESSPYServiceGetPYPayrollCalcLoanResponse retVal = ((KESSPYServices.KESSPYService)(this)).getPYPayrollCalcLoan(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSPYServices.KESSPYServiceGetPYPayrollCalcLoanResponse> KESSPYServices.KESSPYService.getPYPayrollCalcLoanAsync(KESSPYServices.KESSPYServiceGetPYPayrollCalcLoanRequest request)
        {
            return base.Channel.getPYPayrollCalcLoanAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSPYServices.KESSPYServiceGetPYPayrollCalcLoanResponse> getPYPayrollCalcLoanAsync(KESSPYServices.CallContext CallContext, string _emplId)
        {
            KESSPYServices.KESSPYServiceGetPYPayrollCalcLoanRequest inValue = new KESSPYServices.KESSPYServiceGetPYPayrollCalcLoanRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            return ((KESSPYServices.KESSPYService)(this)).getPYPayrollCalcLoanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSPYServices.KESSPYServiceGetPYPayrollCalculationResponse KESSPYServices.KESSPYService.getPYPayrollCalculation(KESSPYServices.KESSPYServiceGetPYPayrollCalculationRequest request)
        {
            return base.Channel.getPYPayrollCalculation(request);
        }
        
        public KESSPYServices.PYPayrollCalculation[] getPYPayrollCalculation(KESSPYServices.CallContext CallContext, string _emplId)
        {
            KESSPYServices.KESSPYServiceGetPYPayrollCalculationRequest inValue = new KESSPYServices.KESSPYServiceGetPYPayrollCalculationRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            KESSPYServices.KESSPYServiceGetPYPayrollCalculationResponse retVal = ((KESSPYServices.KESSPYService)(this)).getPYPayrollCalculation(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSPYServices.KESSPYServiceGetPYPayrollCalculationResponse> KESSPYServices.KESSPYService.getPYPayrollCalculationAsync(KESSPYServices.KESSPYServiceGetPYPayrollCalculationRequest request)
        {
            return base.Channel.getPYPayrollCalculationAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSPYServices.KESSPYServiceGetPYPayrollCalculationResponse> getPYPayrollCalculationAsync(KESSPYServices.CallContext CallContext, string _emplId)
        {
            KESSPYServices.KESSPYServiceGetPYPayrollCalculationRequest inValue = new KESSPYServices.KESSPYServiceGetPYPayrollCalculationRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            return ((KESSPYServices.KESSPYService)(this)).getPYPayrollCalculationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSPYServices.KESSPYServiceGetPyPeriodResponse KESSPYServices.KESSPYService.getPyPeriod(KESSPYServices.KESSPYServiceGetPyPeriodRequest request)
        {
            return base.Channel.getPyPeriod(request);
        }
        
        public KESSPYServices.PyPeriod[] getPyPeriod(KESSPYServices.CallContext CallContext)
        {
            KESSPYServices.KESSPYServiceGetPyPeriodRequest inValue = new KESSPYServices.KESSPYServiceGetPyPeriodRequest();
            inValue.CallContext = CallContext;
            KESSPYServices.KESSPYServiceGetPyPeriodResponse retVal = ((KESSPYServices.KESSPYService)(this)).getPyPeriod(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSPYServices.KESSPYServiceGetPyPeriodResponse> KESSPYServices.KESSPYService.getPyPeriodAsync(KESSPYServices.KESSPYServiceGetPyPeriodRequest request)
        {
            return base.Channel.getPyPeriodAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSPYServices.KESSPYServiceGetPyPeriodResponse> getPyPeriodAsync(KESSPYServices.CallContext CallContext)
        {
            KESSPYServices.KESSPYServiceGetPyPeriodRequest inValue = new KESSPYServices.KESSPYServiceGetPyPeriodRequest();
            inValue.CallContext = CallContext;
            return ((KESSPYServices.KESSPYService)(this)).getPyPeriodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KESSPYServices.KESSPYServiceNewPYPayslipReportResponse KESSPYServices.KESSPYService.newPYPayslipReport(KESSPYServices.KESSPYServiceNewPYPayslipReportRequest request)
        {
            return base.Channel.newPYPayslipReport(request);
        }
        
        public string newPYPayslipReport(KESSPYServices.CallContext CallContext, KESSPYServices.PYPayrollCalculation _payrollCalculationModel)
        {
            KESSPYServices.KESSPYServiceNewPYPayslipReportRequest inValue = new KESSPYServices.KESSPYServiceNewPYPayslipReportRequest();
            inValue.CallContext = CallContext;
            inValue._payrollCalculationModel = _payrollCalculationModel;
            KESSPYServices.KESSPYServiceNewPYPayslipReportResponse retVal = ((KESSPYServices.KESSPYService)(this)).newPYPayslipReport(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSPYServices.KESSPYServiceNewPYPayslipReportResponse> KESSPYServices.KESSPYService.newPYPayslipReportAsync(KESSPYServices.KESSPYServiceNewPYPayslipReportRequest request)
        {
            return base.Channel.newPYPayslipReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSPYServices.KESSPYServiceNewPYPayslipReportResponse> newPYPayslipReportAsync(KESSPYServices.CallContext CallContext, KESSPYServices.PYPayrollCalculation _payrollCalculationModel)
        {
            KESSPYServices.KESSPYServiceNewPYPayslipReportRequest inValue = new KESSPYServices.KESSPYServiceNewPYPayslipReportRequest();
            inValue.CallContext = CallContext;
            inValue._payrollCalculationModel = _payrollCalculationModel;
            return ((KESSPYServices.KESSPYService)(this)).newPYPayslipReportAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_KESSPYService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_KESSPYService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://7.172.65.217:8202/DynamicsAx/Services/KESSPYServices");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KESSPYServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_KESSPYService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KESSPYServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_KESSPYService);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_KESSPYService,
        }
    }
}
