//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KESSMPPServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object
    {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private string PartitionKeyField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser
        {
            get
            {
                return this.LogonAsUserField;
            }
            set
            {
                this.LogonAsUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MPPEmpl", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class MPPEmpl : KESSMPPServices.XppObjectBase
    {
        
        private System.DateTime BirthDateField;
        
        private System.DateTime CBDateField;
        
        private KESSMPPServices.KESSCBType CBTypeField;
        
        private string DepartmentField;
        
        private string DescriptionField;
        
        private string DocumentPathField;
        
        private string EmplIdField;
        
        private string EmplNameField;
        
        private System.DateTime MPPDateEndField;
        
        private System.DateTime MPPDateStartField;
        
        private string MPPIdField;
        
        private KESSMPPServices.KESSMPPStatus MPPStatusField;
        
        private KESSMPPServices.KESSMppType MPPTypeField;
        
        private string PositionField;
        
        private string PositionIdField;
        
        private long RecIdField;
        
        private System.DateTime ScheduleDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CBDate
        {
            get
            {
                return this.CBDateField;
            }
            set
            {
                this.CBDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSMPPServices.KESSCBType CBType
        {
            get
            {
                return this.CBTypeField;
            }
            set
            {
                this.CBTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentPath
        {
            get
            {
                return this.DocumentPathField;
            }
            set
            {
                this.DocumentPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplId
        {
            get
            {
                return this.EmplIdField;
            }
            set
            {
                this.EmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplName
        {
            get
            {
                return this.EmplNameField;
            }
            set
            {
                this.EmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MPPDateEnd
        {
            get
            {
                return this.MPPDateEndField;
            }
            set
            {
                this.MPPDateEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MPPDateStart
        {
            get
            {
                return this.MPPDateStartField;
            }
            set
            {
                this.MPPDateStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MPPId
        {
            get
            {
                return this.MPPIdField;
            }
            set
            {
                this.MPPIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSMPPServices.KESSMPPStatus MPPStatus
        {
            get
            {
                return this.MPPStatusField;
            }
            set
            {
                this.MPPStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSMPPServices.KESSMppType MPPType
        {
            get
            {
                return this.MPPTypeField;
            }
            set
            {
                this.MPPTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionId
        {
            get
            {
                return this.PositionIdField;
            }
            set
            {
                this.PositionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ScheduleDate
        {
            get
            {
                return this.ScheduleDateField;
            }
            set
            {
                this.ScheduleDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSMPPServices.MPPEmpl))]
    public partial class XppObjectBase : object
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSCBType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSCBType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwoMonth = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThreeMonth = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSMPPStatus", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSMPPStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KESSMppType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum KESSMppType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SixMonth = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwelveMonth = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object
    {
        
        private string CustomDetailXmlField;
        
        private KESSMPPServices.FaultMessageList[] FaultMessageListArrayField;
        
        private KESSMPPServices.InfologMessage[] InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml
        {
            get
            {
                return this.CustomDetailXmlField;
            }
            set
            {
                this.CustomDetailXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSMPPServices.FaultMessageList[] FaultMessageListArray
        {
            get
            {
                return this.FaultMessageListArrayField;
            }
            set
            {
                this.FaultMessageListArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSMPPServices.InfologMessage[] InfologMessageList
        {
            get
            {
                return this.InfologMessageListField;
            }
            set
            {
                this.InfologMessageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType
        {
            get
            {
                return this.XppExceptionTypeField;
            }
            set
            {
                this.XppExceptionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object
    {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private KESSMPPServices.FaultMessage[] FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation
        {
            get
            {
                return this.DocumentOperationField;
            }
            set
            {
                this.DocumentOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSMPPServices.FaultMessage[] FaultMessageArray
        {
            get
            {
                return this.FaultMessageArrayField;
            }
            set
            {
                this.FaultMessageArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation
        {
            get
            {
                return this.ServiceOperationField;
            }
            set
            {
                this.ServiceOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter
        {
            get
            {
                return this.ServiceOperationParameterField;
            }
            set
            {
                this.ServiceOperationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine
        {
            get
            {
                return this.XmlLineField;
            }
            set
            {
                this.XmlLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition
        {
            get
            {
                return this.XmlPositionField;
            }
            set
            {
                this.XmlPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object
    {
        
        private KESSMPPServices.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSMPPServices.InfologMessageType InfologMessageType
        {
            get
            {
                return this.InfologMessageTypeField;
            }
            set
            {
                this.InfologMessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="KESSMPPServices.KESSMPPService")]
    public interface KESSMPPService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSMPPService/getMPPList", ReplyAction="http://tempuri.org/KESSMPPService/getMPPListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSMPPServices.AifFault), Action="http://tempuri.org/KESSMPPService/getMPPListAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSMPPServices.KESSMPPServiceGetMPPListResponse getMPPList(KESSMPPServices.KESSMPPServiceGetMPPListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSMPPService/getMPPList", ReplyAction="http://tempuri.org/KESSMPPService/getMPPListResponse")]
        System.Threading.Tasks.Task<KESSMPPServices.KESSMPPServiceGetMPPListResponse> getMPPListAsync(KESSMPPServices.KESSMPPServiceGetMPPListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSMPPService/getMPPByRecId", ReplyAction="http://tempuri.org/KESSMPPService/getMPPByRecIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSMPPServices.AifFault), Action="http://tempuri.org/KESSMPPService/getMPPByRecIdAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSMPPServices.KESSMPPServiceGetMPPByRecIdResponse getMPPByRecId(KESSMPPServices.KESSMPPServiceGetMPPByRecIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSMPPService/getMPPByRecId", ReplyAction="http://tempuri.org/KESSMPPService/getMPPByRecIdResponse")]
        System.Threading.Tasks.Task<KESSMPPServices.KESSMPPServiceGetMPPByRecIdResponse> getMPPByRecIdAsync(KESSMPPServices.KESSMPPServiceGetMPPByRecIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSMPPService/getMPPListByStatus", ReplyAction="http://tempuri.org/KESSMPPService/getMPPListByStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSMPPServices.AifFault), Action="http://tempuri.org/KESSMPPService/getMPPListByStatusAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSMPPServices.KESSMPPServiceGetMPPListByStatusResponse getMPPListByStatus(KESSMPPServices.KESSMPPServiceGetMPPListByStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSMPPService/getMPPListByStatus", ReplyAction="http://tempuri.org/KESSMPPService/getMPPListByStatusResponse")]
        System.Threading.Tasks.Task<KESSMPPServices.KESSMPPServiceGetMPPListByStatusResponse> getMPPListByStatusAsync(KESSMPPServices.KESSMPPServiceGetMPPListByStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSMPPService/getMPPByEmplId", ReplyAction="http://tempuri.org/KESSMPPService/getMPPByEmplIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSMPPServices.AifFault), Action="http://tempuri.org/KESSMPPService/getMPPByEmplIdAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSMPPServices.KESSMPPServiceGetMPPByEmplIdResponse getMPPByEmplId(KESSMPPServices.KESSMPPServiceGetMPPByEmplIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSMPPService/getMPPByEmplId", ReplyAction="http://tempuri.org/KESSMPPService/getMPPByEmplIdResponse")]
        System.Threading.Tasks.Task<KESSMPPServices.KESSMPPServiceGetMPPByEmplIdResponse> getMPPByEmplIdAsync(KESSMPPServices.KESSMPPServiceGetMPPByEmplIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSMPPService/getMPPById", ReplyAction="http://tempuri.org/KESSMPPService/getMPPByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSMPPServices.AifFault), Action="http://tempuri.org/KESSMPPService/getMPPByIdAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        KESSMPPServices.KESSMPPServiceGetMPPByIdResponse getMPPById(KESSMPPServices.KESSMPPServiceGetMPPByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSMPPService/getMPPById", ReplyAction="http://tempuri.org/KESSMPPService/getMPPByIdResponse")]
        System.Threading.Tasks.Task<KESSMPPServices.KESSMPPServiceGetMPPByIdResponse> getMPPByIdAsync(KESSMPPServices.KESSMPPServiceGetMPPByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSMPPServiceGetMPPListRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSMPPServiceGetMPPListRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSMPPServices.CallContext CallContext;
        
        public KESSMPPServiceGetMPPListRequest()
        {
        }
        
        public KESSMPPServiceGetMPPListRequest(KESSMPPServices.CallContext CallContext)
        {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSMPPServiceGetMPPListResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSMPPServiceGetMPPListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSMPPServices.MPPEmpl[] response;
        
        public KESSMPPServiceGetMPPListResponse()
        {
        }
        
        public KESSMPPServiceGetMPPListResponse(KESSMPPServices.MPPEmpl[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSMPPServiceGetMPPByRecIdRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSMPPServiceGetMPPByRecIdRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSMPPServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public long recId;
        
        public KESSMPPServiceGetMPPByRecIdRequest()
        {
        }
        
        public KESSMPPServiceGetMPPByRecIdRequest(KESSMPPServices.CallContext CallContext, long recId)
        {
            this.CallContext = CallContext;
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSMPPServiceGetMPPByRecIdResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSMPPServiceGetMPPByRecIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSMPPServices.MPPEmpl[] response;
        
        public KESSMPPServiceGetMPPByRecIdResponse()
        {
        }
        
        public KESSMPPServiceGetMPPByRecIdResponse(KESSMPPServices.MPPEmpl[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSMPPServiceGetMPPListByStatusRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSMPPServiceGetMPPListByStatusRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSMPPServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSMPPServices.KESSMPPStatus status;
        
        public KESSMPPServiceGetMPPListByStatusRequest()
        {
        }
        
        public KESSMPPServiceGetMPPListByStatusRequest(KESSMPPServices.CallContext CallContext, KESSMPPServices.KESSMPPStatus status)
        {
            this.CallContext = CallContext;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSMPPServiceGetMPPListByStatusResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSMPPServiceGetMPPListByStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSMPPServices.MPPEmpl[] response;
        
        public KESSMPPServiceGetMPPListByStatusResponse()
        {
        }
        
        public KESSMPPServiceGetMPPListByStatusResponse(KESSMPPServices.MPPEmpl[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSMPPServiceGetMPPByEmplIdRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSMPPServiceGetMPPByEmplIdRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSMPPServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string EmplId;
        
        public KESSMPPServiceGetMPPByEmplIdRequest()
        {
        }
        
        public KESSMPPServiceGetMPPByEmplIdRequest(KESSMPPServices.CallContext CallContext, string EmplId)
        {
            this.CallContext = CallContext;
            this.EmplId = EmplId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSMPPServiceGetMPPByEmplIdResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSMPPServiceGetMPPByEmplIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSMPPServices.MPPEmpl[] response;
        
        public KESSMPPServiceGetMPPByEmplIdResponse()
        {
        }
        
        public KESSMPPServiceGetMPPByEmplIdResponse(KESSMPPServices.MPPEmpl[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSMPPServiceGetMPPByIdRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSMPPServiceGetMPPByIdRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSMPPServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string MPPId;
        
        public KESSMPPServiceGetMPPByIdRequest()
        {
        }
        
        public KESSMPPServiceGetMPPByIdRequest(KESSMPPServices.CallContext CallContext, string MPPId)
        {
            this.CallContext = CallContext;
            this.MPPId = MPPId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSMPPServiceGetMPPByIdResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSMPPServiceGetMPPByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSMPPServices.MPPEmpl[] response;
        
        public KESSMPPServiceGetMPPByIdResponse()
        {
        }
        
        public KESSMPPServiceGetMPPByIdResponse(KESSMPPServices.MPPEmpl[] response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface KESSMPPServiceChannel : KESSMPPServices.KESSMPPService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class KESSMPPServiceClient : System.ServiceModel.ClientBase<KESSMPPServices.KESSMPPService>, KESSMPPServices.KESSMPPService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KESSMPPServiceClient() : 
                base(KESSMPPServiceClient.GetDefaultBinding(), KESSMPPServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_KESSMPPService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSMPPServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(KESSMPPServiceClient.GetBindingForEndpoint(endpointConfiguration), KESSMPPServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSMPPServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KESSMPPServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSMPPServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KESSMPPServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSMPPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public KESSMPPServices.KESSMPPServiceGetMPPListResponse getMPPList(KESSMPPServices.KESSMPPServiceGetMPPListRequest request)
        {
            return base.Channel.getMPPList(request);
        }
        
        public System.Threading.Tasks.Task<KESSMPPServices.KESSMPPServiceGetMPPListResponse> getMPPListAsync(KESSMPPServices.KESSMPPServiceGetMPPListRequest request)
        {
            return base.Channel.getMPPListAsync(request);
        }
        
        public KESSMPPServices.KESSMPPServiceGetMPPByRecIdResponse getMPPByRecId(KESSMPPServices.KESSMPPServiceGetMPPByRecIdRequest request)
        {
            return base.Channel.getMPPByRecId(request);
        }
        
        public System.Threading.Tasks.Task<KESSMPPServices.KESSMPPServiceGetMPPByRecIdResponse> getMPPByRecIdAsync(KESSMPPServices.KESSMPPServiceGetMPPByRecIdRequest request)
        {
            return base.Channel.getMPPByRecIdAsync(request);
        }
        
        public KESSMPPServices.KESSMPPServiceGetMPPListByStatusResponse getMPPListByStatus(KESSMPPServices.KESSMPPServiceGetMPPListByStatusRequest request)
        {
            return base.Channel.getMPPListByStatus(request);
        }
        
        public System.Threading.Tasks.Task<KESSMPPServices.KESSMPPServiceGetMPPListByStatusResponse> getMPPListByStatusAsync(KESSMPPServices.KESSMPPServiceGetMPPListByStatusRequest request)
        {
            return base.Channel.getMPPListByStatusAsync(request);
        }
        
        public KESSMPPServices.KESSMPPServiceGetMPPByEmplIdResponse getMPPByEmplId(KESSMPPServices.KESSMPPServiceGetMPPByEmplIdRequest request)
        {
            return base.Channel.getMPPByEmplId(request);
        }
        
        public System.Threading.Tasks.Task<KESSMPPServices.KESSMPPServiceGetMPPByEmplIdResponse> getMPPByEmplIdAsync(KESSMPPServices.KESSMPPServiceGetMPPByEmplIdRequest request)
        {
            return base.Channel.getMPPByEmplIdAsync(request);
        }
        
        public KESSMPPServices.KESSMPPServiceGetMPPByIdResponse getMPPById(KESSMPPServices.KESSMPPServiceGetMPPByIdRequest request)
        {
            return base.Channel.getMPPById(request);
        }
        
        public System.Threading.Tasks.Task<KESSMPPServices.KESSMPPServiceGetMPPByIdResponse> getMPPByIdAsync(KESSMPPServices.KESSMPPServiceGetMPPByIdRequest request)
        {
            return base.Channel.getMPPByIdAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_KESSMPPService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_KESSMPPService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://7.172.65.217:8202/DynamicsAx/Services/KESSMPPServices");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KESSMPPServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_KESSMPPService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KESSMPPServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_KESSMPPService);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_KESSMPPService,
        }
    }
}
