//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KESSTMServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object
    {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private string PartitionKeyField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser
        {
            get
            {
                return this.LogonAsUserField;
            }
            set
            {
                this.LogonAsUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMAbsenImported", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class TMAbsenImported : KESSTMServices.XppObjectBase
    {
        
        private int ClockField;
        
        private string EmplIdField;
        
        private string EmplNameField;
        
        private string InOutField;
        
        private System.DateTime PresenceDateField;
        
        private long RecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Clock
        {
            get
            {
                return this.ClockField;
            }
            set
            {
                this.ClockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplId
        {
            get
            {
                return this.EmplIdField;
            }
            set
            {
                this.EmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplName
        {
            get
            {
                return this.EmplNameField;
            }
            set
            {
                this.EmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InOut
        {
            get
            {
                return this.InOutField;
            }
            set
            {
                this.InOutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PresenceDate
        {
            get
            {
                return this.PresenceDateField;
            }
            set
            {
                this.PresenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSTMServices.TMEmplScheduleDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSTMServices.TMEmplScheduleSubordinate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSTMServices.TMMasterPeriod))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSTMServices.TMPublicHoliday))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KESSTMServices.TMAbsenImported))]
    public partial class XppObjectBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMEmplScheduleDetail", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class TMEmplScheduleDetail : KESSTMServices.XppObjectBase
    {
        
        private string AbsenceCodeIdField;
        
        private int ClockINField;
        
        private int ClockOUTField;
        
        private int DaysField;
        
        private string DocumentPathField;
        
        private string EmplIdField;
        
        private string EmplNameField;
        
        private KESSTMServices.NoYes HolidayField;
        
        private KESSTMServices.NoYes LeaveField;
        
        private KESSTMServices.NoYes NormalField;
        
        private int NormalINField;
        
        private int NormalOUTField;
        
        private long RecIdField;
        
        private string SchedulePatternIdField;
        
        private System.DateTime TransDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbsenceCodeId
        {
            get
            {
                return this.AbsenceCodeIdField;
            }
            set
            {
                this.AbsenceCodeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClockIN
        {
            get
            {
                return this.ClockINField;
            }
            set
            {
                this.ClockINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClockOUT
        {
            get
            {
                return this.ClockOUTField;
            }
            set
            {
                this.ClockOUTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Days
        {
            get
            {
                return this.DaysField;
            }
            set
            {
                this.DaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentPath
        {
            get
            {
                return this.DocumentPathField;
            }
            set
            {
                this.DocumentPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplId
        {
            get
            {
                return this.EmplIdField;
            }
            set
            {
                this.EmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplName
        {
            get
            {
                return this.EmplNameField;
            }
            set
            {
                this.EmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSTMServices.NoYes Holiday
        {
            get
            {
                return this.HolidayField;
            }
            set
            {
                this.HolidayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSTMServices.NoYes Leave
        {
            get
            {
                return this.LeaveField;
            }
            set
            {
                this.LeaveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSTMServices.NoYes Normal
        {
            get
            {
                return this.NormalField;
            }
            set
            {
                this.NormalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NormalIN
        {
            get
            {
                return this.NormalINField;
            }
            set
            {
                this.NormalINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NormalOUT
        {
            get
            {
                return this.NormalOUTField;
            }
            set
            {
                this.NormalOUTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchedulePatternId
        {
            get
            {
                return this.SchedulePatternIdField;
            }
            set
            {
                this.SchedulePatternIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransDate
        {
            get
            {
                return this.TransDateField;
            }
            set
            {
                this.TransDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMEmplScheduleSubordinate", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class TMEmplScheduleSubordinate : KESSTMServices.XppObjectBase
    {
        
        private string AbsenceCodeIdField;
        
        private int ClockINField;
        
        private int ClockOUTField;
        
        private int DaysField;
        
        private string EmplIdField;
        
        private string EmplNameField;
        
        private KESSTMServices.NoYes HolidayField;
        
        private KESSTMServices.NoYes NormalField;
        
        private int NormalINField;
        
        private int NormalOUTField;
        
        private long RecIdField;
        
        private string ReportToEmplIdField;
        
        private string ReportToEmplNameField;
        
        private System.DateTime TransDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbsenceCodeId
        {
            get
            {
                return this.AbsenceCodeIdField;
            }
            set
            {
                this.AbsenceCodeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClockIN
        {
            get
            {
                return this.ClockINField;
            }
            set
            {
                this.ClockINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClockOUT
        {
            get
            {
                return this.ClockOUTField;
            }
            set
            {
                this.ClockOUTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Days
        {
            get
            {
                return this.DaysField;
            }
            set
            {
                this.DaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplId
        {
            get
            {
                return this.EmplIdField;
            }
            set
            {
                this.EmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmplName
        {
            get
            {
                return this.EmplNameField;
            }
            set
            {
                this.EmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSTMServices.NoYes Holiday
        {
            get
            {
                return this.HolidayField;
            }
            set
            {
                this.HolidayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSTMServices.NoYes Normal
        {
            get
            {
                return this.NormalField;
            }
            set
            {
                this.NormalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NormalIN
        {
            get
            {
                return this.NormalINField;
            }
            set
            {
                this.NormalINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NormalOUT
        {
            get
            {
                return this.NormalOUTField;
            }
            set
            {
                this.NormalOUTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportToEmplId
        {
            get
            {
                return this.ReportToEmplIdField;
            }
            set
            {
                this.ReportToEmplIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportToEmplName
        {
            get
            {
                return this.ReportToEmplNameField;
            }
            set
            {
                this.ReportToEmplNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransDate
        {
            get
            {
                return this.TransDateField;
            }
            set
            {
                this.TransDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMMasterPeriod", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class TMMasterPeriod : KESSTMServices.XppObjectBase
    {
        
        private System.DateTime EndDateField;
        
        private string PeriodIdField;
        
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PeriodId
        {
            get
            {
                return this.PeriodIdField;
            }
            set
            {
                this.PeriodIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMPublicHoliday", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class TMPublicHoliday : KESSTMServices.XppObjectBase
    {
        
        private string DescriptionField;
        
        private System.DateTime HolidayDateField;
        
        private System.DateTime YearsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HolidayDate
        {
            get
            {
                return this.HolidayDateField;
            }
            set
            {
                this.HolidayDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Years
        {
            get
            {
                return this.YearsField;
            }
            set
            {
                this.YearsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoYes", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    public enum NoYes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object
    {
        
        private string CustomDetailXmlField;
        
        private KESSTMServices.FaultMessageList[] FaultMessageListArrayField;
        
        private KESSTMServices.InfologMessage[] InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml
        {
            get
            {
                return this.CustomDetailXmlField;
            }
            set
            {
                this.CustomDetailXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSTMServices.FaultMessageList[] FaultMessageListArray
        {
            get
            {
                return this.FaultMessageListArrayField;
            }
            set
            {
                this.FaultMessageListArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSTMServices.InfologMessage[] InfologMessageList
        {
            get
            {
                return this.InfologMessageListField;
            }
            set
            {
                this.InfologMessageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType
        {
            get
            {
                return this.XppExceptionTypeField;
            }
            set
            {
                this.XppExceptionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object
    {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private KESSTMServices.FaultMessage[] FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation
        {
            get
            {
                return this.DocumentOperationField;
            }
            set
            {
                this.DocumentOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSTMServices.FaultMessage[] FaultMessageArray
        {
            get
            {
                return this.FaultMessageArrayField;
            }
            set
            {
                this.FaultMessageArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation
        {
            get
            {
                return this.ServiceOperationField;
            }
            set
            {
                this.ServiceOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter
        {
            get
            {
                return this.ServiceOperationParameterField;
            }
            set
            {
                this.ServiceOperationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine
        {
            get
            {
                return this.XmlLineField;
            }
            set
            {
                this.XmlLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition
        {
            get
            {
                return this.XmlPositionField;
            }
            set
            {
                this.XmlPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object
    {
        
        private KESSTMServices.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KESSTMServices.InfologMessageType InfologMessageType
        {
            get
            {
                return this.InfologMessageTypeField;
            }
            set
            {
                this.InfologMessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="KESSTMServices.KESSTMService")]
    public interface KESSTMService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSTMService/getTMAbsenImported", ReplyAction="http://tempuri.org/KESSTMService/getTMAbsenImportedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSTMServices.AifFault), Action="http://tempuri.org/KESSTMService/getTMAbsenImportedAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMAbsenImportedResponse> getTMAbsenImportedAsync(KESSTMServices.KESSTMServiceGetTMAbsenImportedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSTMService/getTMEmplScheduleDetail", ReplyAction="http://tempuri.org/KESSTMService/getTMEmplScheduleDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSTMServices.AifFault), Action="http://tempuri.org/KESSTMService/getTMEmplScheduleDetailAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMEmplScheduleDetailResponse> getTMEmplScheduleDetailAsync(KESSTMServices.KESSTMServiceGetTMEmplScheduleDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSTMService/getTMMasterPeriodTable", ReplyAction="http://tempuri.org/KESSTMService/getTMMasterPeriodTableResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSTMServices.AifFault), Action="http://tempuri.org/KESSTMService/getTMMasterPeriodTableAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMMasterPeriodTableResponse> getTMMasterPeriodTableAsync(KESSTMServices.KESSTMServiceGetTMMasterPeriodTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSTMService/getTMEmplScheduleSubordinate", ReplyAction="http://tempuri.org/KESSTMService/getTMEmplScheduleSubordinateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSTMServices.AifFault), Action="http://tempuri.org/KESSTMService/getTMEmplScheduleSubordinateAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMEmplScheduleSubordinateResponse> getTMEmplScheduleSubordinateAsync(KESSTMServices.KESSTMServiceGetTMEmplScheduleSubordinateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KESSTMService/getTMPublicHoliday", ReplyAction="http://tempuri.org/KESSTMService/getTMPublicHolidayResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KESSTMServices.AifFault), Action="http://tempuri.org/KESSTMService/getTMPublicHolidayAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMPublicHolidayResponse> getTMPublicHolidayAsync(KESSTMServices.KESSTMServiceGetTMPublicHolidayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSTMServiceGetTMAbsenImportedRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSTMServiceGetTMAbsenImportedRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSTMServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _emplId;
        
        public KESSTMServiceGetTMAbsenImportedRequest()
        {
        }
        
        public KESSTMServiceGetTMAbsenImportedRequest(KESSTMServices.CallContext CallContext, string _emplId)
        {
            this.CallContext = CallContext;
            this._emplId = _emplId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSTMServiceGetTMAbsenImportedResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSTMServiceGetTMAbsenImportedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSTMServices.TMAbsenImported[] response;
        
        public KESSTMServiceGetTMAbsenImportedResponse()
        {
        }
        
        public KESSTMServiceGetTMAbsenImportedResponse(KESSTMServices.TMAbsenImported[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSTMServiceGetTMEmplScheduleDetailRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSTMServiceGetTMEmplScheduleDetailRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSTMServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _emplId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public System.DateTime _startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public System.DateTime _endDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public bool _holidayOnly;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public bool _leaveOnly;
        
        public KESSTMServiceGetTMEmplScheduleDetailRequest()
        {
        }
        
        public KESSTMServiceGetTMEmplScheduleDetailRequest(KESSTMServices.CallContext CallContext, string _emplId, System.DateTime _startDate, System.DateTime _endDate, bool _holidayOnly, bool _leaveOnly)
        {
            this.CallContext = CallContext;
            this._emplId = _emplId;
            this._startDate = _startDate;
            this._endDate = _endDate;
            this._holidayOnly = _holidayOnly;
            this._leaveOnly = _leaveOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSTMServiceGetTMEmplScheduleDetailResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSTMServiceGetTMEmplScheduleDetailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSTMServices.TMEmplScheduleDetail[] response;
        
        public KESSTMServiceGetTMEmplScheduleDetailResponse()
        {
        }
        
        public KESSTMServiceGetTMEmplScheduleDetailResponse(KESSTMServices.TMEmplScheduleDetail[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSTMServiceGetTMMasterPeriodTableRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSTMServiceGetTMMasterPeriodTableRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSTMServices.CallContext CallContext;
        
        public KESSTMServiceGetTMMasterPeriodTableRequest()
        {
        }
        
        public KESSTMServiceGetTMMasterPeriodTableRequest(KESSTMServices.CallContext CallContext)
        {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSTMServiceGetTMMasterPeriodTableResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSTMServiceGetTMMasterPeriodTableResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSTMServices.TMMasterPeriod[] response;
        
        public KESSTMServiceGetTMMasterPeriodTableResponse()
        {
        }
        
        public KESSTMServiceGetTMMasterPeriodTableResponse(KESSTMServices.TMMasterPeriod[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSTMServiceGetTMEmplScheduleSubordinateRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSTMServiceGetTMEmplScheduleSubordinateRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSTMServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _emplId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public System.DateTime _startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public System.DateTime _endDate;
        
        public KESSTMServiceGetTMEmplScheduleSubordinateRequest()
        {
        }
        
        public KESSTMServiceGetTMEmplScheduleSubordinateRequest(KESSTMServices.CallContext CallContext, string _emplId, System.DateTime _startDate, System.DateTime _endDate)
        {
            this.CallContext = CallContext;
            this._emplId = _emplId;
            this._startDate = _startDate;
            this._endDate = _endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSTMServiceGetTMEmplScheduleSubordinateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSTMServiceGetTMEmplScheduleSubordinateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSTMServices.TMEmplScheduleSubordinate[] response;
        
        public KESSTMServiceGetTMEmplScheduleSubordinateResponse()
        {
        }
        
        public KESSTMServiceGetTMEmplScheduleSubordinateResponse(KESSTMServices.TMEmplScheduleSubordinate[] response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSTMServiceGetTMPublicHolidayRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSTMServiceGetTMPublicHolidayRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public KESSTMServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.DateTime years;
        
        public KESSTMServiceGetTMPublicHolidayRequest()
        {
        }
        
        public KESSTMServiceGetTMPublicHolidayRequest(KESSTMServices.CallContext CallContext, System.DateTime years)
        {
            this.CallContext = CallContext;
            this.years = years;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KESSTMServiceGetTMPublicHolidayResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class KESSTMServiceGetTMPublicHolidayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public KESSTMServices.TMPublicHoliday[] response;
        
        public KESSTMServiceGetTMPublicHolidayResponse()
        {
        }
        
        public KESSTMServiceGetTMPublicHolidayResponse(KESSTMServices.TMPublicHoliday[] response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface KESSTMServiceChannel : KESSTMServices.KESSTMService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class KESSTMServiceClient : System.ServiceModel.ClientBase<KESSTMServices.KESSTMService>, KESSTMServices.KESSTMService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KESSTMServiceClient() : 
                base(KESSTMServiceClient.GetDefaultBinding(), KESSTMServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_KESSTMService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSTMServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(KESSTMServiceClient.GetBindingForEndpoint(endpointConfiguration), KESSTMServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSTMServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KESSTMServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSTMServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KESSTMServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KESSTMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMAbsenImportedResponse> KESSTMServices.KESSTMService.getTMAbsenImportedAsync(KESSTMServices.KESSTMServiceGetTMAbsenImportedRequest request)
        {
            return base.Channel.getTMAbsenImportedAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMAbsenImportedResponse> getTMAbsenImportedAsync(KESSTMServices.CallContext CallContext, string _emplId)
        {
            KESSTMServices.KESSTMServiceGetTMAbsenImportedRequest inValue = new KESSTMServices.KESSTMServiceGetTMAbsenImportedRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            return ((KESSTMServices.KESSTMService)(this)).getTMAbsenImportedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMEmplScheduleDetailResponse> KESSTMServices.KESSTMService.getTMEmplScheduleDetailAsync(KESSTMServices.KESSTMServiceGetTMEmplScheduleDetailRequest request)
        {
            return base.Channel.getTMEmplScheduleDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMEmplScheduleDetailResponse> getTMEmplScheduleDetailAsync(KESSTMServices.CallContext CallContext, string _emplId, System.DateTime _startDate, System.DateTime _endDate, bool _holidayOnly, bool _leaveOnly)
        {
            KESSTMServices.KESSTMServiceGetTMEmplScheduleDetailRequest inValue = new KESSTMServices.KESSTMServiceGetTMEmplScheduleDetailRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            inValue._startDate = _startDate;
            inValue._endDate = _endDate;
            inValue._holidayOnly = _holidayOnly;
            inValue._leaveOnly = _leaveOnly;
            return ((KESSTMServices.KESSTMService)(this)).getTMEmplScheduleDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMMasterPeriodTableResponse> KESSTMServices.KESSTMService.getTMMasterPeriodTableAsync(KESSTMServices.KESSTMServiceGetTMMasterPeriodTableRequest request)
        {
            return base.Channel.getTMMasterPeriodTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMMasterPeriodTableResponse> getTMMasterPeriodTableAsync(KESSTMServices.CallContext CallContext)
        {
            KESSTMServices.KESSTMServiceGetTMMasterPeriodTableRequest inValue = new KESSTMServices.KESSTMServiceGetTMMasterPeriodTableRequest();
            inValue.CallContext = CallContext;
            return ((KESSTMServices.KESSTMService)(this)).getTMMasterPeriodTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMEmplScheduleSubordinateResponse> KESSTMServices.KESSTMService.getTMEmplScheduleSubordinateAsync(KESSTMServices.KESSTMServiceGetTMEmplScheduleSubordinateRequest request)
        {
            return base.Channel.getTMEmplScheduleSubordinateAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMEmplScheduleSubordinateResponse> getTMEmplScheduleSubordinateAsync(KESSTMServices.CallContext CallContext, string _emplId, System.DateTime _startDate, System.DateTime _endDate)
        {
            KESSTMServices.KESSTMServiceGetTMEmplScheduleSubordinateRequest inValue = new KESSTMServices.KESSTMServiceGetTMEmplScheduleSubordinateRequest();
            inValue.CallContext = CallContext;
            inValue._emplId = _emplId;
            inValue._startDate = _startDate;
            inValue._endDate = _endDate;
            return ((KESSTMServices.KESSTMService)(this)).getTMEmplScheduleSubordinateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMPublicHolidayResponse> KESSTMServices.KESSTMService.getTMPublicHolidayAsync(KESSTMServices.KESSTMServiceGetTMPublicHolidayRequest request)
        {
            return base.Channel.getTMPublicHolidayAsync(request);
        }
        
        public System.Threading.Tasks.Task<KESSTMServices.KESSTMServiceGetTMPublicHolidayResponse> getTMPublicHolidayAsync(KESSTMServices.CallContext CallContext, System.DateTime years)
        {
            KESSTMServices.KESSTMServiceGetTMPublicHolidayRequest inValue = new KESSTMServices.KESSTMServiceGetTMPublicHolidayRequest();
            inValue.CallContext = CallContext;
            inValue.years = years;
            return ((KESSTMServices.KESSTMService)(this)).getTMPublicHolidayAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_KESSTMService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_KESSTMService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://7.172.65.217:8202/DynamicsAx/Services/KESSTMServices");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KESSTMServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_KESSTMService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KESSTMServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_KESSTMService);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_KESSTMService,
        }
    }
}
